### ISSUE TITLE
Linked collections are not displaying in the target Dataverse in the UI

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse.harvard.edu#104]
https://dataverse.harvard.edu/dataverse/CGIAR

I linked numerous collections to this Dataverse in 2020, within the "sub Dataverse collections" and now they are not showing up.

Attempting to link again does not show the needed Dataverse collection, indicating the linking already exists.

As an  example, Try linking these to this collection 
https://dataverse.harvard.edu/dataverse/CGIAR_centers 
and you will see the collection is not available to link to:

o   Africa Rice Center - https://dataverse.harvard.edu/dataverse/AfricaRice

o   Alliance of Bioversity International and CIAT - https://dataverse.harvard.edu/dataverse/AllianceBioversityCIAT

o   Bioversity International - https://dataverse.harvard.edu/dataverse/Bioversity

**Comment by scolapasta** [comment]
This seems to be because of https://github.com/IQSS/dataverse/issues/7766

**Comment by djbrooke** [comment]
Closing in favor of #7766
