### ISSUE TITLE
Loading versions tab is slow

### ISSUE THREAD

**Issue by joeHickson** [IQSS/dataverse.harvard.edu#106]
Please allow for pagination - particularly with daily updates this list is getting big and VERY slow to load.
example: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/S07EZB

**Comment by jggautier** [comment]
Related to https://github.com/IQSS/dataverse/issues/8328

**Comment by sbarbosadataverse** [comment]
The "waste management" dataset is a great example of the versions tab not loading due to how versioning is being used

**Comment by sbarbosadataverse** [comment]
@cmbz do we add an spa label to this?
