### ISSUE TITLE
Configure "View Data" and "PDF Preview" tools as "Preview Only" in Harvard Dataverse to help clarify the experience of previewing vs. exploring data

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse.harvard.edu#108]
There was a lot of work done in [#6919](https://github.com/IQSS/dataverse/issues/6919) to help clarify the use and role of Previews vs. Explore tools. In order to achieve the desired user experience goals outlined in that issue for Harvard Dataverse users, I think we need to configure the View Data external tool as "preview only" as outlined in the issue and pull request [#7369](https://github.com/IQSS/dataverse/pull/7369).

**Comment by qqmyers** [comment]
FWIW: The dev branch of the dataverse-previewers repo has example curl commands to register previewers as type preview only (and not also as an explore tool): https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers/blob/develop/5.2curlcommands.md

**Comment by djbrooke** [comment]
- pull a list of the tools enabled on dataverse.harvard.edu and make decisions for each 
- cut and paste from the above branch (thanks @qqmyers!)

**Comment by TaniaSchlatter** [comment]
I reviewed on production, looking at the files/file types in this [example doc](https://docs.google.com/presentation/d/1si64aNf2NtWWHFVYhM1MMbq_shZ2ni7fxgejGaPp7ys/edit#slide=id.p). I wonder who might benefit from the "Open in New Window" feature, and about making the Explore option more obvious, but this works for now.
