### ISSUE TITLE
file tab display of image for "restricted file" is cluttered when not logged in for access

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse.harvard.edu#110]
When I log in and have access to the file, this issue is not visible.

Dataset for example: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/AJHKU6

<img width="2348" alt="Screen Shot 2021-05-07 at 4 17 24 PM" src="https://user-images.githubusercontent.com/8322346/117506964-70d43080-af54-11eb-8d4b-bb93e4f3a487.png">

**Comment by TaniaSchlatter** [comment]
Yikes! I don't see it in Chrome, Firefox, or Safari.

**Comment by jggautier** [comment]
I [wrote in Slack](https://iqss.slack.com/archives/GRDNRJ6BZ/p1620419947171900) that I wasn't able to reproduce it for a few other datasets I checked but I am for this dataset, at least in Chrome (Version 90.0.4430.93 (Official Build) (x86_64)).

**Comment by jggautier** [comment]
I see a lot more datasets whose file tables have this bug when I [search for restricted PDF files](https://dataverse.harvard.edu/dataverse/harvard?q=&fq0=dvObjectType%3A%28files%29&fq1=fileTypeGroupFacet%3A%22Document%22&fq2=fileAccess%3A%22Restricted%22&types=files&sort=dateSort&order=desc).

And hovering over the broken images, it's like the image previewer is also broken:

<kbd><img width="704" alt="Screen Shot 2021-05-07 at 5 40 28 PM" src="https://user-images.githubusercontent.com/18374574/117511336-86992400-af5b-11eb-8a74-1d7dc37d048d.png"></kbd>

**Comment by sbarbosadataverse** [comment]
> Yikes! I don't see it in Chrome, Firefox, or Safari.

I am using Chrome.

**Comment by qqmyers** [comment]
FYI: I found this after merging 5.4 at QDR and unfortunately assumed it was related to the customizations there. I just created an[ issue ](https://github.com/IQSS/dataverse/issues/7859)and [PR](https://github.com/IQSS/dataverse/pull/7860) to fix it.

**Comment by mreekie** [comment]
This issue can simply be closed.
It has been previously fixed.
