### ISSUE TITLE
Investigate Anonymous Review feature for use on Harvard Dataverse Repository 

### ISSUE THREAD

**Issue by kmika11** [IQSS/dataverse.harvard.edu#119]
Version 5.6 includes a feature to generate a Private URL that allows a user to “Create URL for Anonymized Access” for a dataset (https://guides.dataverse.org/en/5.6/user/dataset-management.html#private-url-for-reviewing-an-unpublished-dataset). To enable that feature we need a list of metadata fields to "hide." The Demo server is already updated to 5.6 and could be a good place to test once we have a list of fields drafted.

**Comment by kmika11** [comment]
List of metadata fields to anonymize: author, authorName, authorAffiliation, authorIdentifier, datasetContact, datasetContactName, datasetContactAffiliation, publication, publicationCitation, publicationIDNumber, publicationURL, producer, producerName, producerAffiliation, producerAbbreviation, producerURL, producerLogoURL, contributor, contributorName, grantNumber, grantNumberAgency, grantNumberValue, distributor, distributorName, distributorAffiliation, distributorAbbreviation, distributorURL, distributorLogoURL, depositor, relatedMaterial, relatedDatasets, otherReferences, dataCollector, astroFacility. 

Turns out there's a lot of ways to identify a creator! The complete list is also available here: https://docs.google.com/spreadsheets/d/1_87zwn6WkHY242a3tmyKvMTyUgyMzTj7itoP7QcbLHc/edit#gid=0

**Comment by jggautier** [comment]
Thanks! The two issues have been created at https://github.com/IQSS/dataverse/issues/8184 and https://github.com/IQSS/dataverse/issues/8185. @djbrooke I agree this issue can be closed. What do you think @kmika11?

**Comment by kmika11** [comment]
Thanks all! Yes, @jggautier I agree this can be closed.
