### ISSUE TITLE
Turn File PID minting on in Harvard Dataverse, Mint PIDs for files that don't have them

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#12]
- Let's turn File PIDs back on in Harvard Dataverse
- Let's mint PIDs for files that didn't get PIDs while it was turned off in Harvard Dataverse

**Comment by kcondon** [comment]
File PIDs are now enabled in prod.
Not sure yet about achieving the second part, creating PIDs for files that do not have them.

**Comment by landreev** [comment]
I was going to run a script for registering the individual published files that were skipped; similarly to the scripts I ran for the older files, hdl datasets, etc.

**Comment by landreev** [comment]
Ok, the registration (of the existing published, unregistered files) is running. 
(the more recent ones are being registered first). 
How is this "small" anyway?  This is a monumental, herculean task. It took 4 months just to get to it.

**Comment by pdurbin** [comment]
As discussed at standup, we're documenting the endpoints in https://github.com/IQSS/dataverse/issues/5835

**Comment by landreev** [comment]
The batch registration job finished last week.

**Comment by djbrooke** [comment]
Thanks @landreev, I moved this to QA.
