### ISSUE TITLE
For one dataset, certain pages of files in the file table are not loading

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#131]
To reproduce this on prod:

- Go to https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/6FZWGJ
- Scroll down to the file table and try to navigate to page 2 or 7
- It returns you to page 1

There is a banner at top that this could not be registered with DataCite, and I believe these files were added during a period of instability (in Aug 2020). There's some chatter in Slack that it was a case of https://github.com/IQSS/dataverse/issues/7551, so I will ask the reporter if I can try to publish. It's also possible that a file on those pages is corrupted or something 🤔 . I'm starting with this issue in the dataverse.harvard.edu repo because I think it's a data thing and not a code thing, but I will move it if needed. 

Also, I can provide a private URL on request for the above dataset if needed. The issue happens there as well.

**Comment by pdurbin** [comment]
From server.log: `javax.el.ELException: /file-info-fragment.xhtml @63,95 value=" - #{fileMetadata.dataFile.friendlySize}": java.lang.NullPointerException`

Filesize was -1 (null) for 10 files. @landreev fixed them. I can now page through the files using a Private URL. @djbrooke I'm moving this to Review and giving it to you to close or whatever.

**Comment by djbrooke** [comment]
Closing, thank you!
