### ISSUE TITLE
Update Previewers on dataverse.harvard.edu, demo.dataverse.org

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#136]
See https://groups.google.com/g/dataverse-community/c/CDvd6TSC34I for more info.

**Comment by sbarbosadataverse** [comment]
@scolapasta I would be interested in adding this to HDV!

**Comment by scolapasta** [comment]
@sbarbosadataverse note this isn't "adding" anything. Just updating the current tools. This does come with some minor improvements.

**Comment by sbarbosadataverse** [comment]
I haven't seen it in use yet...so it is on HDV? @scolapasta

**Comment by scolapasta** [comment]
Yes, these are the previewers that have been on HDV (and demo) for a long while now. For example when you go to image file page and see the "preview".  It's just changing to the latest version (and a new location)

**Comment by scolapasta** [comment]
OK, updates made to both Harvard Dataverse and Demo Dataverse.  A total of 17 entires were updated (though several are repeats for different mime types, i.e. ImagePreview for jpeg, png, gif, etc.)

I'll pass this to QA, just so someone (@kcondon) can verify that it all looks ok.

But basically, if you go to a previewer (e.g. file page for an image, click on "open in new window), you'll see the URL has changed, for example for images:
from:
https://globaldataversecommunityconsortium.github.io/dataverse-previewers/previewers/ImagePreview.html?...
to:
https://gdcc.github.io/dataverse-previewers/previewers/v1.2/ImagePreview.html?...
