### ISSUE TITLE
File Provenance not working on demo

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse.harvard.edu#138]
When I selected Provenance from the File page Edit menu on demo (newly created dataset, small image file), I was able to enter info in the "Provenance Description' field, but when I hit 'Continue' I got an error popup saying that there were no changes. This isn't happening on my test box running off dev, or at QDR which is at ~5.8. At QDR, I tried to verify that this is not related to the #8276 Embargo setting issue - textual provenance updates work there with the embargo setting not set or if it is set to 0.

I'm not sure what this could be - at QDR, the provenance menu entry does go away if I set the :ProvCollectionEnabled setting to 'false', so it doesn't seem to be a bug in when the menu item shows.

I don't know what other settings could be involved or if this is really a v5.8 issue (if so, it would have to be one that is fixed in develop and at QDR which between 5.8 and 5.9 w.r.t. changes from github.com/IQSS).

**Comment by sbarbosadataverse** [comment]
Gustavo said to wait on this until we decide how we will support Provance after the SPA

**Comment by qqmyers** [comment]
This doesn't seem to be occurring in 6.2 - suggest we close this.

**Comment by pdurbin** [comment]
Fine by me. Closing.
