### ISSUE TITLE
Migrate the test Handlenet instance to a new home

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#141]
It is currently running on dvn-vm7.hmdc.harvard.edu (140.247.115.130) which is scheduled to be retired. The plan is to move to dataverse-internal. 
The migration on our end is trivial (just copying the contents of the directory and the startup files). But we then need to contact handlenet to switch the registration for the name space to the new ip address (I have the contact for that).

**Comment by landreev** [comment]
Copied everything onto dataverse-internal. I'll try to re-register the service with handlent, but we may need to figure out who the dedicated contact is for that name space; because it doesn't look like it was me.

**Comment by landreev** [comment]
(so, should be safe to nuke the local instance, I think...)

**Comment by landreev** [comment]
Just a status update, there was a delay with this because the new server was not exposed to the world properly. That was fixed, I resubmitted the registration info so it should be resolved shortly.

**Comment by landreev** [comment]
OK, it should be properly registered at the new location now. 
Thanks for the assistance with the port config, @kcondon. 
There is no PR associated with the issue; I'll move into into QA - to quickly retest publishing a dataset with a handle on dataverse-internal, maybe? 
No configuration changes are needed on a system that's already configured to use this naming prefix. (All it needs is the prefix itself, and the private key for talking to the service; the location of the local server is determined dynamically).

**Comment by kcondon** [comment]
Thanks @landreev this works on internal. The logs are a bit noisy but then again, haven't checked them for this provider in quite a while. Thanks again!
