### ISSUE TITLE
Unable to remove datasets that Harvard Dataverse Repository harvested from Swedish National Data Service 

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#142]
From the Harvard Dataverse Repository's "Manage Harvesting Clients" page, I deleted the client that was created to harvest datasets from the Swedish National Data Service. An administrator from that repository asked us to remove it. I didn't see any error message in the UI and the the client was removed from the list (at https://dataverse.harvard.edu/harvestclients.xhtml).

But so far none of the 468 datasets harvested into the collection at https://dataverse.harvard.edu/dataverse/SND have been removed.

Is there anything from the logs or database that could explain why the records haven't been removed? This is the first time I've run into this problem.

**Comment by jggautier** [comment]
In the short term, just to improve the search experience for people looking for data (by removing stale records that point to an error page) I can try to use the destroy dataset API endpoint to remove all of the harvested records at https://dataverse.harvard.edu/dataverse/SND.

Would that make it harder to figure out why deleting the client didn't result in those harvests being removed?

**Comment by landreev** [comment]
I'm assuming it cannot be deleted or managed via normal mechanisms because it is one of the fake Nesstar-based harvested dataverses that were migrated from DVN3 years ago. I just opened an issue requesting to purge all of them (#153). It will likely require some manual API or database-level effort.

**Comment by sbarbosadataverse** [comment]
What's the likelihood this issue will be fixed with the Harvesting updates in progress? @mreekie @siacus 
We don't want to add this to the Dataverse Backlog for Harvard Dataverse if they may get fixed by the harvesting updates.

Thanks

**Comment by cmbz** [comment]
2023/12/19: This issue will likely be superseded by: #153

**Comment by cmbz** [comment]
Closing as per note about #153

**Comment by pdurbin** [comment]
This issue has been closed but it's still in the sprint ready column. I'll remove it.
