### ISSUE TITLE
Add metadatablock for 3D data for Boston College

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#144]
I'm working with librarians from Boston College to add a custom metadatablock that can be used to describe the 3D data they're depositing in a collection in the Harvard Dataverse Repository.

**Comment by pdurbin** [comment]
Just a heads up that Sherry from UVa and Jamie from UCLA have both expressed interest in 3D files: https://groups.google.com/g/dataverse-community/c/71kuJ6TdUIg/m/1NtdQPEcBAAJ

**Comment by jggautier** [comment]
The custom metadatablock is ready to be added to the Harvard Dataverse Repository and available only in the collection specified in the TSV file. The metadatablock's TSV and properties files are in the Dataverse GitHub repo, in a branch at https://github.com/IQSS/dataverse/tree/3d-custom-metadatablock. I added them there when I thought we needed to add them as part of a Dataverse software release, but @scolapasta let me know we can apply the changes to the Harvard Dataverse Repository without adding them to the software release.

I'm not sure where to put the TSV and properties files if they shouldn't go in the Dataverse repo. I'm also attaching them in a zip file in this comment: [custom3d_metadatablock_tsv_and_properties.zip](https://github.com/IQSS/dataverse.harvard.edu/files/8201286/custom3d_metadatablock_tsv_and_properties.zip).

@scolapasta could you let me know? Also, please let me know if there's anything else I can do to help get the new metadatablock added. I'm helping with a custom metadatablock for another Dataverse collection that I think may be ready to add in the next month or so.

I'm thinking that once this "3d data" metadatablock is added to the Harvard repository, I can write in [that Google Group thread](https://groups.google.com/g/dataverse-community/c/71kuJ6TdUIg/m/1NtdQPEcBAAJ) that the new fields are in use and it might be helpful for those folks to take a look at how it's working for describing this kind of data.

**Comment by scolapasta** [comment]
@jggautier we can upload the block whenever you want. As for where to put them in a repo, we should discuss this with the team, but my inclination would be to start moving custom blocks into the harvard dv repo. We can discuss at a future tech hours.

**Comment by jggautier** [comment]
Thanks, I think you mentioned that this might be discussed during this week tech hours. If it is and if I'd be helpful if I join, let me know :)

The block has been reviewed with the collection administrators and can be uploaded as soon as it's technically possible. They don't have any hard deadlines but would like some estimate about when the new fields can be added so they can plan when to start adding datasets.

**Comment by mreekie** [comment]
Def of done:
  **Do 144 first:**

Define the process:
- [X] Create finalized tsv file
- [ ] Determine where to keep the metadatablock in source control (needs to be done only once for 144, 145)
- [ ] file it in source control

Test in QA:
- [ ] Run the API to upload the blocks in QA
- [ ] Kevin will do this in the test environment first
- [ ] Update solar in QA

Apply to production
- [ ] Run the API to upload the blocks in Production
- [ ] Update solar in QA

The process is documented in the guides.

related:
 - #145  
- #144

**Comment by mreekie** [comment]
size=small

**Comment by scolapasta** [comment]
Here's my proposal for source control:
• add a new directory to this repo for metadatablocks
• add the new metadatablock tsv file to this directory
• add a setup-harvard script that includes calling this (for when we want to create a server that emulates harvard)
• eventually transition all the existing custom blocks to this repo / setup script from the core dataverse repo (tbd, should this be part of this issue or separate?)

**Comment by pdurbin** [comment]
I believe the pull request I just made covers the source control proposal above:

- #152 

I loaded up 3D Objects Metadata block locally and it looks good:

![Screen Shot 2022-04-14 at 2 38 27 PM](https://user-images.githubusercontent.com/21006/163457613-398ba06e-d952-4c92-ba60-a69d5ecafae2.png)

The block is called `custom3d` but if we like how it's going in production at Harvard Dataverse, we could potentially rename the block (remove "custom") and move it into the main git repo, document it in the guides, etc.

**Comment by shlake** [comment]
I'll add more comments tomorrow, but FYI there is a group setting community standards for 3D data - metadata: https://cs3dp.org/metadata/ and they have a forthcoming book: https://cs3dp.org/books/

I'm going to contact them members of the metadata group to see if I an get a draft of their chapter in this forthcoming 3D data standard book.

@jggautier do you know if anyone from BC is in this 3D community?

**Comment by shlake** [comment]
Here's the chapter "Metadata Requirements for 3D Data" for the forthcoming book:
http://doi.org/10.34944/dspace/6733
I'm looking through it now comparing to the custom 3D block above.

**Comment by shlake** [comment]
@jggautier Please let the google group know about this new metadata block to get more opinions.

I am not sure what you were going to calling the block, but I suggest that the block not be called just "3D data". This limited set of fields is definitely limited in scope of 3D data and is focused on an artifact or similar "smaller" object. 

These fields would not work for most of the large scale 3D data that is being collected and added to UVa's Dataverse repository (point cloud data for buildings and large scale subject matter). Which is fine, just means that UVa might need to create a different 3D metadata block - which has been on my to-do list for quite awhile.

**Comment by jggautier** [comment]
Hi @shlake. The admins of the Dataverse collection in the Harvard Dataverse Repository reviewed some research on standards for describing 3D data but I'm not sure if they or anyone else from BC are in that 3D community you mentioned. I'll ask them today.

Those collection admins are using "3D Objects Metadata" as the display name for the metadatablock. I put "custom3d" as its database name. The plan is to make the metadatablock available only for the one Dataverse collection in the Harvard Dataverse Repository since they need it to continue depositing datasets. The metadatablock won't be available for other collections in the Harvard repo and won't be shipped with the Dataverse software.

I planned that once this "3d data" metadatablock is added to the Harvard repository, I can write in [that Google Group thread](https://groups.google.com/g/dataverse-community/c/71kuJ6TdUIg/m/1NtdQPEcBAAJ) that the new fields are in use and it might be helpful for those who are interested to take a look at how it's working for describing this kind of data.

In the Google Group thread I can also mention that chapter of the forthcoming book, unless you'd like to.

**Comment by pdurbin** [comment]
@jggautier thanks for posting to the mailing list: https://groups.google.com/g/dataverse-community/c/7MOqMhZTTaA/m/kIYyxuz0KQAJ
