### ISSUE TITLE
Some datasets are uneditable, have finalizePublication lock, but DOIs work, "Draft"/"Unpublished" labels are missing

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#150]
These datasets are published but are unable to be edited (through the GUI):
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/A3NWA7
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VYNLON
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/RC0WLY
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/28MPKM
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/NVMNMP
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/LTMCFR
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/79CRQJ
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DEAZAQ
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/XGA4CH
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/58YPIG
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/APJNDT
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/H2JL7A
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/AGJPZH
- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/XPOLYI

More info:
- Logged in users with permission to edit the dataset see a "Publish in Progress" yellow warning banner:
  <img width="1157" alt="Screen Shot 2022-12-05 at 11 00 17 AM" src="https://user-images.githubusercontent.com/18374574/205683400-8541454d-bc67-4745-92ff-fc7a0e6e8295.png">
- The datasets' DOI URLs lead to the datasets
- The datasets' files are downloadable by anyone ("guest" users)
- The API endpoint for reporting dataset locks reports that there are finalizePublication locks on these dataset 

@scolapasta and @landreev, I haven't "unlocked" these dataset in case seeing it in this state is helpful for a developer who can take a closer look at what's happening. But please let me know if that's not needed and I can use the endpoint to "unlock" this dataset to try to make it editable again.

Definition of done:
- These datasets are able to be edited, the "Publish in Progress" yellow warning banners are removed, and the finalizePublication locks are removed

**Comment by jggautier** [comment]
This dataset no longer appears locked. Not sure what happened. Asking around now

**Comment by jggautier** [comment]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VYNLON is another dataset published last week that's like the dataset described in this issue's first comment. It's published, so the DOI points to the landing page, but it's not editable.

I haven't tried to "unlock" this dataset in case a developer wanted to take a closer look at what was happening.

**Comment by jggautier** [comment]
Another dataset at https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/RC0WLY

**Comment by jggautier** [comment]
Another dataset at https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/1EKMTZ

**Comment by sbarbosadataverse** [comment]
@scolapasta @lenwiz @mreekie 
this was reported back in April and is considered a blocker.

**Comment by mreekie** [comment]
Sizing:
- Came from dataverse.harvard.edu
- This needs to start with an investigation of the harvard.edu instance.
- Scope: fix the harvard instance and then timebox an investigation
-  size: 10

**Comment by scolapasta** [comment]
@jggautier I just discussed this with @landreev and we agree that, based on the DOIs and files working, that these can be safely unlocked. Since this is almost a year old, there's no need to investigate what happened with these. Of course, if this happens again with any newer datasets, let us know.

**Comment by jggautier** [comment]
Thanks @scolapasta. I've been adding to that list of datasets since I opened this issue, including one from this morning.

I can unlock the datasets that are listed. And if more are like this, should I open a new issue?

**Comment by scolapasta** [comment]
@jggautier I think it depends on the circumstances - e.g. we've recently had lots of restarts in prod and that often causes locks to stay, i.e. the lock gets created, the server gets restarted, and so the running process that would've removed the lock gets stopped. With the call to datacite for the doi, it's usually fine because once we send that, that doesn't get stopped.

So, in my opinion, if this happens, you can check with the team if there's been a recent restart. If so, and everything checks out, I'd say ok to just remove the lock. If it happens more often and when we don't see server restarts, then it is more worthy of an investigation.

**Comment by jggautier** [comment]
Okay. I'll try to unlock the datasets now.

**Comment by jggautier** [comment]
They're all unlocked.
