### ISSUE TITLE
ADD GeoJSON previewer To Demo and Harvard Dataverse, related to #136

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse.harvard.edu#157]
**What kind of user is the feature intended for?**
API User, Curator, Depositor, Guest, Superuser, Sysadmin

**What inspired the request?
requests for geospatial collections needing this tool

**What existing behavior do you want changed?**
ADD TO DEMO AND HARVARD DATAVERSE

**Any brand new behavior do you want to add to Dataverse?**
NO

**Any related open or closed issues to this feature request?**

- https://github.com/IQSS/dataverse.harvard.edu/issues/136

**Comment by mreekie** [comment]
sprint
 - configuring a tool that is already created.
 - size is small
 -

**Comment by landreev** [comment]
@sbarbosadataverse 
The previewer "https://gdcc.github.io/dataverse-previewers/previewers/v1.3/MapPreview.html" has been added to demo and prod. 
As seen here on a GeoJSON file in prod.:
https://dataverse.harvard.edu/file.xhtml?fileId=6292862&version=3.0

**Comment by landreev** [comment]
I'm going to close the issue, but please let me know or reopen if I missed anything.
