### ISSUE TITLE
Username Merging and Username Renaming in dataverse.harvard.edu

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#16]
In a future release, we'll introduce code changes (https://github.com/IQSS/dataverse/issues/3575) that will no longer allow the same username to be used with different capitalization. In preparation for this, we added new APIs for renaming and merging in 4.12 (https://github.com/IQSS/dataverse/issues/5514 and https://github.com/IQSS/dataverse/issues/5515).

We need to use these APIs to rename or merge users that have the same usernames in dataverse.harvard.edu before we release the new DB constraint.

**Comment by djbrooke** [comment]
Generally, the steps I'll take are:

- Run the query to determine which duplicate accounts exist
- Determine which ones need to be merged because they are the same person and which need to be renamed because they are different people
- Fix
- Rerun the query right before the release that contains #3575 to make sure that no others have snuck in and repeat the above steps if needed

**Comment by djbrooke** [comment]
Almost all done! One case left. Will finish as soon as the person gets back to me.

**Comment by djbrooke** [comment]
OK, I've resolved all of these in Harvard Dataverse. 

@kcondon if you'd like to verify, feel free.  I'm also OK moving this to Done.  Up to you!

**Comment by kcondon** [comment]
@djbrooke Can you post the duplicate checking query? I'd like to run it. Also, I'm generally ok with your process but can you send me a pointer to your merge doc so I can just look at a couple accounts? Thanks!

**Comment by djbrooke** [comment]
@kcondon Sure, I sent you the merged/rename accounts over Slack, note there are two sheets. I also sent on the query (running to a meeting but will link to the public version here as well).

**Comment by kcondon** [comment]
Thanks, just wanted to see what the before and after looked like. Looks good!
