### ISSUE TITLE
Let depositors of datasets in the Boston College Dataverse collection enter any text into the custom 3D Objects metadata block's Material Composition field

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#163]
The Material Composition field in the custom 3D Objects metadata block lets depositor choose only one material from the field's controlled vocabulary.

The administrators of the Boston College Dataverse collection asked that we change the Material Composition field so that depositors can type in a material in a text box and so that they can enter multiple materials (change the field's allowMultiple property to TRUE).

I created a PR at https://github.com/IQSS/dataverse.harvard.edu/pull/164 that edits the TSV file.

Then it looks like the curl command in the Admin Guide's section about [reloading a metadatablock](https://guides.dataverse.org/en/5.10.1/admin/metadatacustomization.html#reloading-a-metadata-block) will need to be run to apply the change, such as `curl http://localhost:8080/api/admin/datasetfield/load -H "Content-type: text/tab-separated-values" -X POST --upload-file custom3d.tsv`

Does anything else need to be done to apply the change?

**Comment by jggautier** [comment]
The collection administrators just asked me to revise this request to make the field a free text field that allows multiple values. I'll update the PR for this, at https://github.com/IQSS/dataverse.harvard.edu/pull/164.

**Comment by mreekie** [comment]
() a recently added metadata block - after being added - ppl using it wanted a certain field to be changed.
() Gustavo and Julian discussed with customer.
() sounds like it comes in as a small. 
() Customer is waiting patiently - this came in from the community meeting.  We need to do this to be responsive to the community.  If they start using this before being fixed it willbe harder to fix later.
