### ISSUE TITLE
When creating, editing and viewing datasets in the NegotiationDataRepository collection, its custom metadatablock appears above the Citation metadatablock

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#165]
When creating, editing and viewing datasets in [the Negotiation Data Repository collection](https://dataverse.harvard.edu/dataverse/NegotiationDataRepository), its custom metadatablock appears above the Citation metadatablock:

<details>
<summary>Screenshot of page when creating or editing a dataset in the NDR collection:</summary

<kbd><img width="780" alt="Screen Shot 2022-05-16 at 7 25 02 PM" src="https://user-images.githubusercontent.com/18374574/168698102-2bface7e-0e1f-4d55-9ef8-7264b809dcdf.png"></kbd>
</details>

<details>
<summary>Screenshot of page when viewing a dataset in the NDR collection:</summary>

<kbd><img width="961" alt="Screen Shot 2022-05-16 at 7 35 31 PM" src="https://user-images.githubusercontent.com/18374574/168698972-5f44754d-dda0-429e-a8e3-80ddf7e211b8.png"></kbd>
</details>

When creating and viewing datasets in other collections that have custom metadatablocks, the Citation block still appears first, even when there are fields in the other custom metadatablocks that are set to displayoncreate, such as the [Healthy Birth, Growth & Development knowledge integration Dataverse](https://dataverse.harvard.edu/dataverse/HBGDki) and [its custom metadatablock](https://github.com/IQSS/dataverse/blob/develop/scripts/api/data/metadatablocks/custom_hbgdki.tsv). So this seems to be a bug. This didn't happen when I spun up AWS test Dataverse instances with this custom metadatablock.

And when viewing the dataset, the system-generated Dataset Persistent ID and Publication Date fields are at the top. Is this because Dataverse puts the system-generated dataset fields at the top of whichever metadatablock appears first on the page, which happens to be the custom metadatablock in this case?

**Comment by mreekie** [comment]
sprint
 - we don't have a good understanding of the root cause yet.
 - we're going to asssume small going  in.
