### ISSUE TITLE
Edit customNDR metadatablock to correct metadatablock name, remove Study Design field, and make its child fields primitive fields

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#166]
Managers of the [The Negotiation Data Repository](https://dataverse.harvard.edu/dataverse/NegotiationDataRepository) asked for the recently added customNDR metadatablock, the four child fields of the "Study Design" field be their own fields, instead, in order to prevent the design problem described at https://github.com/IQSS/dataverse/issues/6589.

So instead of:

<kbd><img width="947" alt="168840986-fadb82c7-0cdc-4ff0-ba3e-d540abcd04fa" src="https://user-images.githubusercontent.com/18374574/168854840-344ebb51-e9b8-4543-85bc-8b7b2384c87d.png"></kbd>

The "Study Design" field should be removed and the Protocol, Sample Size, Randomization, and Outcomes fields will be simple fields:

<kbd>![Untitled-1](https://user-images.githubusercontent.com/18374574/168854636-e678cee4-e197-4028-b82f-006d0e76fd68.png)</kbd>

I can make a PR in this repository with the edited TSV and properties files. 

Because there's a published dataset at https://doi.org/10.7910/DVN/ZZG2FE with values in these fields, @scolapasta or other developer colleagues, will anything else need to be done for for this dataset? The database names of the four fields aren't changing, so no database edits are needed to move the metadata values in that published dataset, right?

**Comment by mreekie** [comment]
sprint
- Gustavo estimates this as a small
- Possibly a db script required.
-

**Comment by jggautier** [comment]
In the PR at https://github.com/IQSS/dataverse.harvard.edu/pull/167, I edited the customNDR TSV and properties files to make this change.

**Comment by jggautier** [comment]
@kcondon wondered if because the PR also changes the name of the metadatablock, will the default dataset template for one of NDR's Dataverse collection's ([Negotiation Journal](https://dataverse.harvard.edu/dataverse/NegotiationJournal)) also need to be re-created?

If/once these metadatablock changes are implemented on the Harvard Dataverse Repository, I'd be happy to check what affect this has on the Negotiation Journal collection's default dataset template and if I should re-create the template again. (More details about adding new metadatablocks and their affect on dataset templates is at https://github.com/IQSS/dataverse/issues/8704)
