### ISSUE TITLE
Make sure Dataverse recognizes geoJson files as geoJson files

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#168]
There are geoJson files in the Harvard Dataverse Repository that Dataverse does not recognize has geoJson files, e.g. https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/YQX0SW/GLBKGD. The file's Type is "unknown". This also prevents Dataverse from creating a preview of the file.

One way to resolve this would be to use [the Redetect File Type endpoint](https://guides.dataverse.org/en/5.10.1/api/native-api.html?highlight=redetect#redetect-file-type) so that Dataverse knows those files are geoJson files.

**Comment by pdurbin** [comment]
@kaitlinnewson (who contributed the GeoJSON previewer) indicated that they (Scholars Portal/Borealis) haven't been able to get their previously deposited GeoJSON files to be redetected and pointed me to this open issue:

- https://github.com/IQSS/dataverse/issues/7527

@landreev already make a pull request but I'm not sure what the status is:

- https://github.com/IQSS/dataverse/pull/7631

**Comment by jggautier** [comment]
I used the endpoint to redetect the filetype of that file at https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/YQX0SW/GLBKGD and it worked.

I'll open a new issue about finding other geoJson files in the Harvard repository that aren't recognized as geoJson files and using the redetect endpoint to make Dataverse recognize them.
