### ISSUE TITLE
Fix the files affected by the 5.11 delete bug in production

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#180]
The bug in question is https://github.com/IQSS/dataverse/issues/8867
A number of files in our own prod. appear to have been affected as well. 
Note that unlike the user who first reported the issue, above - where dataverse was trying to use one of the deleted files as the thumbnail for the dataset - most users would likely not notice anything immediately. 

The second goal of this issue is to put together an instruction to pass to the remaining 2 remote installations that had 5.11 deployed in their production.

**Comment by landreev** [comment]
Took a lot of manual work, but I was able to fix most of the datasets (9 of them).
I will need help communicating with the authors of these two: 
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/H8OFUY
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/X093TV

These are not (easily-)fixable. It appears that it would make sense to ask the authors to junk their latest published versions (or the entire dataset, in the case of H8OFUY).

**Comment by landreev** [comment]
Locked both of the datasets above with some scary locks, to prevent the users from getting into more trouble by attempting to further modify them.

**Comment by landreev** [comment]
got a reply from the author of [X093TV](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/X093TV), he is super understanding/ok with the proposed purging of the last version, and re-uploading the files he tried to add last week. Proceeding.

**Comment by landreev** [comment]
The other dataset, `[H8OFUY](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/H8OFUY) is already on @jggautier's radar (the author appears to have given up on it, and created and published a new dataset with the same content). (RT: https://help.hmdc.harvard.edu/Ticket/Display.html?id=323811). At this point we are waiting to hear back from the author, having suggested to destroy it. If we don't hear back, it will be deleted per standard curation policies. 

So the prod. cleanup can be declared completed. 
I'm going to close this ticket. If any remote installation reaches out and reports that they too have been affected by this bug, I'll work with them on a case-by-case basis. I can't really make a fix script that I could send to everybody preemptively.  The basic fix can be described in one sentence and doesn't need a script: restore the owner_id and recover the files from backups. In practice this would be a different process for everybody. Plus in real life there almost certainly will be unique complications for specific datasets.

**Comment by sbarbosadataverse** [comment]
@landreev 
The curation team will look at these two deposits to contact the authors. Our direct contacts from production could be going to spam:

I will need help communicating with the authors of these two:
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/H8OFUY
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/X093TV
