### ISSUE TITLE
Remove "Study Design" label when editing a dataset's fields in the customNDR metadata block

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#181]
With v5.11 applied to the Harvard repository, the customNDR metadata block was updated to have its "Study Design" parent field removed and its child fields changed to simple fields (https://github.com/IQSS/dataverse.harvard.edu/issues/166)

But after creating a dataset, when you edit its metadata, that Study Design parent field is visible. See the dataset at https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/UQ4UWK:

<kbd><img width="1158" alt="Screen Shot 2022-08-01 at 12 13 28 PM" src="https://user-images.githubusercontent.com/18374574/182198222-8a2eeb0c-2fe3-4cff-80b3-6ef17910d484.png"></kbd>

Can this label be removed from the page when editing the metadata of datasets in the collection?

This Study Design label is not shown on the page when creating a new dataset. It's also not shown when editing dataset templates.

**Comment by scolapasta** [comment]
This was a simple fix - we just had to remove the old parent type from the datasetfieldtype table.

Note: the reuploading of tsv files is useful for adding of updating types, but is not designed to remove types, so it has to be done manually.

@jggautier can you check if this is all set, and if so, close the issue?

**Comment by jggautier** [comment]
It looks set, thanks! That "Study Design" field is no longer there when editing dataset metadata in the collections.
