### ISSUE TITLE
Add SAEF metadata block to Harvard Dataverse Repository

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#185]
After testing of the metadata block is finished, we'll need to add the metadata block to the Harvard Dataverse Repository, to be available only in the repository's SAEF collection (https://dataverse.harvard.edu/dataverse/saef)

A working draft of the metadata block's TSV file is at https://docs.google.com/spreadsheets/d/1Uv8jlADIKgQ6DfgrXiZ14POrR1YQvpfBXgLadIlEz9Y#gid=1851768194

**Comment by jggautier** [comment]
Hey @scolapasta, regarding the custom block you added to Demo Dataverse, would that stay on Demo until we decide to remove it? Would any other process remove that custom block?

For example, there's a notice on Demo's front page that "Datasets older than 30 days will be deleted at 5am EST on the first day of each month." Does that process remove only datasets and wouldn't kind of take the installation back to factory settings so to speak?

**Comment by sbarbosadataverse** [comment]
@scolapasta Hey Gustavo, Just checking on this ticket for completion.

**Comment by landreev** [comment]
@sbarbosadataverse Planning to install it tonight.

**Comment by landreev** [comment]
With all the spam drama (spama?), never confirmed adding the block to prod. 
Please check that it's showing as expected. 

Also, should this block be checked in in this (https://github.com/IQSS/dataverse.harvard.edu) repo?

**Comment by jggautier** [comment]
I can see it listed:

<img width="979" alt="Screen Shot 2022-10-28 at 5 46 18 PM" src="https://user-images.githubusercontent.com/18374574/198738357-39529366-d62a-4689-819f-1a1818b78287.png">

But I think @cmbz can enable it and maybe make sure her scripts for creating datasets with metadata in those new fields work.

I agree, I think the plan was to add custom metadata blocks to this dataverse.harvard.edu repo

**Comment by jggautier** [comment]
This was discussed during this morning's standup meeting and I mentioned that @cmbz has tested this metadata block on Demo Dataverse. So I think this issue was closed because it should work on the Harvard repository since it was already tested on Demo Dataverse.

**Comment by landreev** [comment]
Checked in the block files under /metadatablocks.
