### ISSUE TITLE
In Harvard Dataverse Repository, three published datasets are in unpublished Dataverse collections

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#186]
As far as I know this shouldn't happen. Datasets created in Dataverse collections can't be published if the collection is not published and published datasets can't be moved into unpublished collections.

The three listed below are accessible without logging into the repository. Clicking on the Dataverse collection links at the top of the pages takes me to the repository login page, since the collections are unpublished.

Both non-deaccessioned datasets can be found by searching for their titles. (Searching for deaccessioned datasets doesn't work well, by design.)

https://doi.org/10.7910/DVN/JTPW3N, published in 2016
https://doi.org/10.7910/DVN/YSK071, published in 2008
https://doi.org/10.7910/DVN/0MBNAW, published and its only version deaccessioned in 2017 

I think we could probably email the depositors of the first two and make sure they're aware the datasets are publicly accessible. If they are, we can probably just publish the collection, assuming that works.

For the deaccessioned dataset, all of the other datasets in that collection are unpublished, so we can't publish the collection. And I'm not sure if we can delete the deaccessioned dataset due to a repository curation policy where we shouldn't delete deaccessioned datasets whose files have already been downloaded. @sbarbosadataverse, what do you think?

<details>
  <summary>Here's the query I used to find them:</summary>

```
select
	dataverse.alias,
	dvobject_dataset.identifier,
	dvobject_dataset.createdate, 
	dvobject_dataset.publicationdate
from dataset
join dvobject dvobject_dataset on dvobject_dataset.id = dataset.id
join dataverse on dataverse.id = dvobject_dataset.owner_id
join dvobject dvobject_dataverse on dvobject_dataverse.id = dataverse.id
where
     -- dataset is published
     dvobject_dataset.publicationdate is not null and

     -- dataverse collection is not published
     dvobject_dataverse.publicationdate is null 

order by dataverse.alias, dvobject_dataset.identifier
```
</details>

**Comment by sbarbosadataverse** [comment]
@jggautier I'm adding this to our backlog column to discuss  for a solution

**Comment by jggautier** [comment]
Just an update: I wrote in an earlier comment in August 2022 that we could email the depositors to make sure they know the datasets are publicly available, even when the collection they're in is not published.

I haven't emailed anyone, though I'd be very surprised if they didn't already know that the datasets were public.

**Comment by mreekie** [comment]
Sizing:
- 3 datasets that published and in collections that are unpublished.
- This will be fixing the production problem and looking to see if there's an investigation required.
- This does not happen very often. Root cause if we can find it.
- Help needed! What solution does Sonia and Julian want as an outcome?
- Sizing is a 3
-

**Comment by scolapasta** [comment]
@jggautier I would go ahead and email if the dataverses can be published.

Also you wrote: "For the deaccessioned dataset, all of the other datasets in that collection are unpublished, so we can't publish the collection" - why couldn't we publish the dataverse collection?

**Comment by scolapasta** [comment]
Since these are all old datasets, I don't think an investigation would be useful at this time. (if it happens again, with a newer dataset, then yes).

**Comment by jggautier** [comment]
Sending a reminder email in a week sounds good to me. I'll do that then.

Yeah I don't like leaving the collections published either. Sometimes it messes with results of my database queries.

**Comment by jggautier** [comment]
I emailed the depositors last Thursday. I'll send a reminder email this Thursday.

**Comment by jggautier** [comment]
One of the three depositors got back to me last week (https://help.hmdc.harvard.edu/Ticket/Display.html?id=336196) and I'm trying to figure out if the dataset was a test or for a class and is no longer needed.

I haven't heard from the other two depositors, https://help.hmdc.harvard.edu/Ticket/Display.html?id=336197 and https://help.hmdc.harvard.edu/Ticket/Display.html?id=336198.

**Comment by jggautier** [comment]
Sonia asked me to publish the three collections. I've published them so I'm closing this issue.

I emailed the depositors to let them know.

**Comment by jggautier** [comment]
I'm just noting that I found a few datasets in [Borealis](https://borealisdata.ca/dataverse/dv) that are also in unpublished collections.

I'm emailing their admins to ask if they know.
