### ISSUE TITLE
10.5072 to 10.70122 on non-prod systems

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#19]
We need to move non-prod systems from the soon-to-be retired 10.5072 to our new test prefix, 10.70122. I have set up the test accounts with the help of @jonc1438 and I will share credentials internally.

**Comment by pdurbin** [comment]
There's some related discussion over at https://github.com/IQSS/dataverse/issues/5448

**Comment by landreev** [comment]
I believe this is done. 
@kcondon has already taken care of dataverse-internal, dvn-build and demo; 
I have reconfigured the credentials in domain.xml on dvn-vm5; 
And on phoenix.dataverse.org (even though it's using the "fake"  provider - but just in case). 
It should be the responsibility of the developers to reconfigure their individual build boxes, if/when 10.5072 stops working. (Ask me or Kevin for the credentials, if you need them). 

Did we forget about any other systems? - Let me know.
