### ISSUE TITLE
Deploy 5.12 in production

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#190]
Haven't heard from anyone waiting for anything in 5.12 specifically or being blocked until it's deployed. But would prefer to do it soon-ish regardless. We should just give it a few days, to make sure there's nothing in there that would require an urgent 5.12.1 release.

**Comment by jggautier** [comment]
Safe to close this issue, right? I see Harvard Dataverse is on "v. 5.12 build pirate-(eye)-patch". If not, feel free to re-open.
