### ISSUE TITLE
Restore access to two published datasets' whose pages fail to load; API endpoint for getting their dataset metadata fails

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#192]
The DOIs of two published datasets - doi:10.7910/DVN/26663 and doi:10.7910/DVN/29779 - fail to load:

- https://doi.org/10.7910/DVN/26663 - https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/26663
- https://doi.org/10.7910/DVN/29779 - https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/29779

And the Native API endpoints for getting their metadata return different errors.

- In Splunk, the log for incident ID returned when following https://dataverse.harvard.edu/api/datasets/:persistentId/versions?persistentId=doi:10.7910/DVN/26663 says `"Unmatched closing ')' near index 1"`
- For https://dataverse.harvard.edu/api/datasets/:persistentId/versions?persistentId=doi:10.7910/DVN/29779, I saw `null java.lang.NullPointerException`

Both datasets come up in searches using the UI and the Search API ([search for  doi:10.7910/DVN/26663](https://dataverse.harvard.edu/dataverse/harvard/?q=dsPersistentId:"doi:10.7910/DVN/26663"); [search for doi:10.7910/DVN/29779](https://dataverse.harvard.edu/dataverse/harvard/?q=dsPersistentId:"doi:10.7910/DVN/29779")), and all other datasets in their collections are accessible.

I'm going to try to contact the data owners to let them know that the datasets' pages aren't accessible and that we're looking into it.

@sbarbosadataverse Can restoring access to these datasets be considered in a prioritization meeting?

Context: (from a discussion with @jggautier and @mreekie 
- The depositors did not delete this data. This was not a failed attempt by the depositor or by a dev to delete the data.
- At least some of the data files exist  when I tried to use the APIs to access them.
- It's just that when you click on the links you get error pages and when you use the APIs to get the metadata it fails.

How will we know it's done.
- The data is reachable via the links.

**Comment by pdurbin** [comment]
I'm pretty uncertain what the solution is here. Hopefully, the data is in the database and that null pointer will lead us something we can fix? @landreev and @scolapasta have a lot of experience diagnosing problems like this. Gave it an 80.

**Comment by mreekie** [comment]
Moved size to 33 after input from leonid and gustavo

**Comment by jggautier** [comment]
I suppose https://github.com/IQSS/dataverse.harvard.edu/issues/150 might need the same?

**Comment by landreev** [comment]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/29779 should be fixed

**Comment by landreev** [comment]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/26663 is also fixed

**Comment by landreev** [comment]
(Julian, did you just came across these 2 datasets, or was it based on user reports/complaints? - Just curious. Both of these are very old, migrated datasets, and both had some bad values in the file-level metadata. I'm also positive that they had been like that for a long time)

**Comment by jggautier** [comment]
Just came across them (when using the Dataverse APIs to collect metadata from all published datasets in the repository)
