### ISSUE TITLE
Add ZIP Previewer & File Downloader to demo and prod

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse.harvard.edu#196]
Can we please install the ZIP Previewer & File Downloader on https://demo.dataverse.org and https://dataverse.harvard.edu ?

This:

- https://github.com/gdcc/dataverse-previewers/pull/9

Thanks!!

**Comment by pdurbin** [comment]
I just stumbled upon a live example at https://edmond.mpdl.mpg.de/file.xhtml?fileId=199941&version=11.0

I downloaded the image. Works great!

![Screen Shot 2022-12-22 at 2 55 19 PM](https://user-images.githubusercontent.com/21006/209215798-9ab1c4a4-0716-4fb1-83d5-fcc65cf278c6.png)

![image001](https://user-images.githubusercontent.com/21006/209215816-80692834-5129-4ede-8996-febb68ee2053.jpg)

**Comment by mreekie** [comment]
backlog steward meeting:
 - Added this to Harvard dataverse managed queue

**Comment by landreev** [comment]
(the zip previewer should also be available on both demo and prod. now)

**Comment by pdurbin** [comment]
A bad zip file threw me off at first (only 22 bytes!) but legit zip file works fine on both prod and demo. Thanks, @landreev!

Here's a screenshot:

<img width="1582" alt="Screenshot 2023-02-28 at 12 11 30 PM" src="https://user-images.githubusercontent.com/21006/221926844-a050b161-684e-4d00-98d2-b762a5748160.png">

(It's a little weird that the files are not in alphabetical order.)

Closing.

**Comment by landreev** [comment]
> (It's a little weird that the files are not in alphabetical order.)

It is showing the files in the physical order of how they are stored inside the zip file. I tend to think that this is the correct behavior; FWIW, `zipinfo` does the same thing on the command line.
