### ISSUE TITLE
Production Issues (content abuse, user accounts)

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse.harvard.edu#198]

**Comment by mreekie** [comment]
Transferred issue to dataverse.harvard.edu.

**Comment by landreev** [comment]
As agreed during the tech hour, will open a sub-issue, for implementing disabling collection creation in prod., a temporary measure that will allow reopening local account signups.

**Comment by scolapasta** [comment]
Closing this. As the sub issue mentioned above (implementing disabling collection creation) has been completed, and a 2nd sub issue has been created (and is in the backlog) for purging old, unused accounts.
