### ISSUE TITLE
Disable colleciton creation in production. 

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#199]
(sub-issue of #198). 
This immediate temporary measure will allow reopening local account signups in prod. All collections will have to be created for users by request, but that can be handled by support, without having a developer with superhuman ssh and admin api access abilities.

**Comment by mreekie** [comment]
Leonid - add this onto the dataverse board into In progress whenever you think is right. Production issues skip the queue.

**Comment by landreev** [comment]
The following has been done in production: 
We have disabled free-for-all collection creation for the `:authenticated-users` group where it used to be allowed; dataset creation has been left intact: 
```
DELETE FROM roleassignment WHERE assigneeidentifier=':authenticated-users' AND role_id = 4;
UPDATE roleassignment SET role_id = 5 WHERE assigneeidentifier=':authenticated-users' AND role_id = 3;
```
3 and 4 are the  "full contributors" and "collection contributors" roles. (Saved the roleassignment entries above before deleting/updating, in case we want to restore that setup later). 

Hacked the login page to show the following banner: 

```
<b>Please note:</b> Users are required to contact support to create a collection rather than deposit multiple datasets directly into Harvard root.

<b>Creation of new collections has been <i>partially</i> restricted</b> (in those existing collections where any logged in user used to be able to create one). If you are unable to create a collection, <b>please contact support</b>.
```
This has allowed us to tentatively reopen local account signups. We do need to keep an eye on the accounts that are being created now and/or any uptick in abuse. We should also proceed with #201 - purge any unused accounts that we may have sitting around. 

@scolapasta added a refinement to the above by giving the "collection contributor" role to the shib groups of users from Harvard and a couple of other trusted/prioritized schools. To both make life easier for these users and to lighten the load on support. 

We can point other installations at the above if anyone else is looking for ways to harden access in response to similar situations.

**Comment by jggautier** [comment]
Sorry if this was already brought up. I just noticed that the front page's "Add a Dataverse" button leads to an error page. 

<kbd><img width="972" alt="Screen Shot 2023-01-11 at 1 00 25 PM" src="https://user-images.githubusercontent.com/18374574/211882983-00606c40-279d-448e-9aae-58873800a3ac.png"></kbd>

Some potential depositors have clicked on it and since the banner's not on this page, they don't see that creating collections is disabled and what they need to do.

Should I open a new GitHub issue about this? Or maybe this isn't needed depending on how long collections are disabled?

**Comment by pdurbin** [comment]
@jggautier wow you're right...

![Screen Shot 2023-01-11 at 2 24 21 PM](https://user-images.githubusercontent.com/21006/211899106-49e47eb1-9e76-4e1c-a9db-668bcf368e5e.png)

... I vote for a fresh issue, please, if you don't mind. You could link back to this one.

**Comment by jggautier** [comment]
Do we expect that collection creation will be limited the way it is now for long enough to warrant doing something about the front page?

**Comment by jggautier** [comment]
During a recent team meeting I heard that we expect collection creation to be limited for a long time or permanently. I agreed to open a new GitHub issue about the homepage's "Add a dataverse" button. Doing that asap.
