### ISSUE TITLE
Purge unused user accounts (as in, first consider and discuss, then, potentially, purge)

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#201]
(another sub-issue of #198)
This is something Odum at UNC implemented on their site following problems with inappropriate activity similar to ours. 
They chose to actually *delete* all such accounts (as opposed to _deactivate_), which by definition only works on completely unused accounts (for ex., downloading a single file and the resulting entry in the guestbook table makes an account "un-deletable"). We can do that, or choose to deactivate whatever accounts we deem abandoned; if we choose the latter, we can expand the definition of such. 

Getting rid of unused accounts is generally a good practice. But it would also eliminate any malicious "sleeper" types.

**Comment by mreekie** [comment]
Leonid - add this onto the dataverse board into In progress whenever you think is right. Production issues skip the queue.

**Comment by mreekie** [comment]
Sizing:
- [ ] script to first select, count, and destroy bad accounts.

The effort here will be to ask Don for his script from UNC and then run it here. The destroy account script will only delete accounts that have been created but never used. There may be a couple of rounds and analysis.  We are taking advantage of the work done by UNC on this already so no R&D

There is no review or QA associated with this.

Leonid is the best candidate probably.
This will probably take about a day.

**Comment by mreekie** [comment]
added to sprint Dec 15, 2022
