### ISSUE TITLE
Move Harvard Dataverse Repository from Google Analytics' Universal Analytics to Google Analytics 4

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#202]
Harvard Dataverse Repository is using Google Analytics' Universal Analytics to record aggregated use metrics (pageviews, button clicks, search logs, etc). On July 1, 2023, Universal Analytics will stop processing new hits. Google's urging everyone to move to Google Analytics 4.

More info about switching is at https://support.google.com/analytics/answer/10759417. I haven't read too closely but it looks like in the process Google will transfer use data to Google Analytics 4, and there's guidance for transferring category/action/label events.

@kcondon and I have accounts with access to the Google Analytics' Universal Analytics and I think we can make the move. I don't have permission to see who else has an account with access. Do you @kcondon?

**Comment by kcondon** [comment]
@jggautier Sent permission info outside of ticket.

**Comment by jggautier** [comment]
So multiple people with access to help make the move. Thanks!

**Comment by jggautier** [comment]
The Harvard UX group is hosting a talk in March about "How a UX team implemented GA4", so I'm planning on attending, although reading the description, I'm not sure if they'll spend enough time on details for moving from Universal Analytics to GA4. I suspect it'll mostly be a confirmation that it shouldn't be that tough to do, and the more interesting part will be examples about how to use it more to inform decisions about the design of the repository's features and services.

Here's the registration info:

> URC Lunch & Learn: Where Google Analytics meets UX - How a UX team implemented GA4
> Online. Tuesday, March 14, 2023, 12:00pm - 1:00pm 
> Amy Deschenes, Meg McMahon
> 
> Our library’s move to Google Analytics 4 created an opportunity for the UX team to determine the best analytics strategy for the organization. We’ll share how we learned about cross domain tracking, event creation and using Looker to build dashboards as well as how we established a unified analytics strategy.
> [Register](https://libcal.library.harvard.edu/event/10335611)

**Comment by jggautier** [comment]
@kcondon created a GA4 property. I'm going to close this ticket.

The other Universal Analytics property will keep keep processing data until July 1, 2023, when I'm assuming it'll stop working. I've created page view reports from this data. I think @sbarbosadataverse has, too. And those will stop working, too.

I played with GA4 a bit and before I got too far I started thinking that it'll be easier and make more sense to get pageview data from Harvard Dataverse's implementation of Make Data Count. Hopefully it's available by July!

**Comment by jggautier** [comment]
I wasn't able to attend the Harvard UX group's talk about how it implemented and uses GA4. But they've made the slides and recording available. Links to them are in the Google Doc at  https://docs.google.com/document/d/1RjctfwSv4KhWwb5Mqk2WSOrd5y2xF2s8nZ85NXyvgmg
