### ISSUE TITLE
Spike: Do users who can't create Dataverse collections know this before clicking on homepage's "Add a Dataverse" button?

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#207]
When users log into their accounts...

<kbd><img width="750" alt="Screen Shot 2023-01-17 at 10 13 48 AM" src="https://user-images.githubusercontent.com/18374574/212936163-7db38338-8963-4381-addb-28ae0d7feda6.png"></kbd>

... which don't have permission to create Dataverse collections (https://github.com/IQSS/dataverse.harvard.edu/issues/199), and they click the homepage's "Add Dataverse" button...

<kbd><img width="998" alt="Screen Shot 2023-01-17 at 9 36 42 AM" src="https://user-images.githubusercontent.com/18374574/212927063-3cb46ebc-c57d-488c-8d49-fdfcdcc87766.png"></kbd>

... it leads them to a confusing error page:

<kbd><img width="751" alt="Screen Shot 2023-01-17 at 9 39 12 AM" src="https://user-images.githubusercontent.com/18374574/212927555-c22559ae-07f4-4ba8-bf0e-4433ae7da02a.png"></kbd>

The yellow banner on the login page explains that collection creation is limited. But I heard from a user who was still confused about what happened when they clicked on the "Add a dataverse" button and saw the error page.

During a brief chat about this with the Dataverse team, I heard that we expect collection creation to be limited in the repository for a long time or permanently, so if this is a widespread issue, it's worth improving.

We mentioned some ideas for improving this:
- Removing the homepage's "Add a dataverse" button and the text above it ("Organize datasets...")
- Making the homepage show the button and text only when the logged in user is able to create collections in the "Root" collection
- Improving the error message to let users know that they should contact support to have a collection created for them

We might also look into improving the banner message on the Log In page and how it's delivered, since it's already on a page that all users see. Are most users overlooking it? Are any parts of it unclear?

**Definition of done:**
I'm not sure how widespread this is, so maybe the first step would be to figure that out:
- We could look through the support emails and learn from the curation and support teams if other users are confused.
- We could do some usability tests with users to see if they notice the banner, and when they do, how they interpret what it's saying. Any potential or current users would do. Since the banner was put up, there are also users who might have created multiple datasets in "Harvard root". We could contact them to learn if they noticed the banner and get their feedback on it.

**Comment by pdurbin** [comment]
What if we change the “Add a dataverse” button to have an arrow ↗️  and link to the support site? (This would be like the “Getting started  ↗️” button.) We’d create a page about contacting support, explain the info needed (username, etc.), and we’ll create the dataverse/collection for you. We'd link to a new page, I mean. Something like https://support.dataverse.harvard.edu/add-a-collection

![Screenshot 2023-10-06 at 11 56 32 AM](https://github.com/IQSS/dataverse.harvard.edu/assets/21006/37de76b4-4727-4897-addd-f1c3dc12a438)

**Comment by jggautier** [comment]
One thing I just realized is that when someone clicks the "Sign Up" button to create a new "local" account, as opposed to clicking the "Log In" button to log into one that's already been created, they don't see that yellow banner message at all.

So there might be at least some cases where people are confused because they had no chance to see a message that asks them to contact support to create a collection.

So maybe some message should be added on the "Sign Up" page, too?

**Comment by jggautier** [comment]
Anyone can create collections in Harvard Dataverse now, as of sometime in June 2024, so users don't see these error messages anymore and the challenges I wrote about don't exist anymore. I'm closing this GitHub issue.
