### ISSUE TITLE
Add Badge for DataCite registration provider

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse.harvard.edu#210]
We recently re registered Harvard Dataverse as a DataCite service provider for 2023 and they sent us a badge. Stefano suggested adding it to the site, and Julian suggested on the home page footer. (Details to be worked out with Julian)

This zip contains what they sent:
[datacite_service_provider_badge.zip](https://github.com/IQSS/dataverse.harvard.edu/files/10512502/datacite_service_provider_badge.zip)

The zip contains the badge in two different colors and two different formats (png and svg):
<img src="https://user-images.githubusercontent.com/4268292/214924738-a14a1141-b4ab-4a01-b4a1-995b2cdca9e5.png" width=30% height=30%><img src="https://user-images.githubusercontent.com/4268292/214924888-30d81fc1-78de-4ded-8e3c-32f2cf704c60.png" width=25% height=25%>

**Comment by mreekie** [comment]
sizing:
- can we add this to our front page.
- sizing seems to be a 10:
- This is a production task

**Comment by pdurbin** [comment]
> Julian suggested on the home page footer

Home page footer? I assume what's meant is a custom footer, which Harvard Dataverse doesn't have:

![Screen Shot 2023-06-16 at 12 06 44 PM](https://github.com/IQSS/dataverse.harvard.edu/assets/21006/972ad19f-93e3-492e-a577-e6b6abd79a21)

**Comment by jggautier** [comment]
I looked through a few other Dataverse repositories for examples of footers that show these sorts of badges. Here are two of those repositories:

1. https://edatos.consorciomadrono.es
<kbd><img width="1188" alt="Screenshot 2023-10-11 at 3 36 25 PM" src="https://github.com/IQSS/dataverse.harvard.edu/assets/18374574/60981891-4f54-4869-95ec-1a1d9a04272d"></kbd>

2. https://data.cimmyt.org
<kbd><img width="1180" alt="Screenshot 2023-10-11 at 3 36 47 PM" src="https://github.com/IQSS/dataverse.harvard.edu/assets/18374574/684df6d4-4c45-4fb0-a8cf-561e3d353483"></kbd>

Does this help? I think both of those layouts support the badge that @siacus would like displayed on the repository, and more images could be added later. And maybe it would help to get the code these other repositories used?

**Comment by pdurbin** [comment]
I talked to @jp-tosca and we agree that this should probably go in our custom footer: https://github.com/IQSS/dataverse.harvard.edu/blob/master/customization/harvard-dataverse-footer.html

**Comment by jp-tosca** [comment]
![image](https://github.com/IQSS/dataverse.harvard.edu/assets/142103991/fb450839-89ae-43e7-8e27-8efc201ad05d)

**Comment by cmbz** [comment]
2023/12/12: Moved back into @scolapasta's column for prioritization

**Comment by pdurbin** [comment]
Was a decision made on what to do? Which page to link to, or if to link at all? If the badge should go on prod or dataverse.org or both?
