### ISSUE TITLE
shibb group: create a shibb group for Cornell University

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse.harvard.edu#212]

**Comment by scolapasta** [comment]
OK, added the shib group. I also added the new group to  the all known shib groups group (and gave DV creator role at root, which is needed temporarily until  https://github.com/IQSS/dataverse/issues/9369 is fixed).

This is the json I used:
`{
  "name": "All Cornell University Shibboleth Users",
  "attribute": "Shib-Identity-Provider",
  "pattern": "https://shibidp.cit.cornell.edu/idp/shibboleth"
}` 

@sbarbosadataverse can you please have a Cornell user test and see if it works? (we can know if it works if they can create a dataverse collection at the root level)?
