### ISSUE TITLE
add NcML previewers (HDF5 and NetCDF) to demo and Harvard Dataverse

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse.harvard.edu#213]
I just uploaded and HDF5 file to https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/JTUS2J and the NcML file was correctly extracted...

![Screen Shot 2023-02-15 at 10 16 02 AM](https://user-images.githubusercontent.com/21006/219069332-7d457e47-6b4e-4381-bb0c-70a6d312e16b.png)

... but the eyeball is absent because the NcML previewer hasn't yet been added. Can we please add it to the demo site? I can also open a separate issue for Harvard Dataverse or we can just use this one.

Please note that there are actually two previewers because there are two MIME types in play. The following is copied from https://github.com/gdcc/dataverse-previewers/blob/d8193b1083d0b84443303fc345d8d6d5e12d9f04/5.2curlcommands.md#ncml-previewer-requirements

```
curl -X POST -H 'Content-type: application/json' http://localhost:8080/api/admin/externalTools -d \
'{
  "displayName":"Show NcML (XML)",
  "description":"Metadata from HDF5 files.",
  "toolName":"ncmlPreviewer",
  "scope":"file",
  "types":["preview"],
  "toolUrl":"https://gdcc.github.io/dataverse-previewers/previewers/betatest/NcmlPreview.html",
  "toolParameters": {
      "queryParameters":[
        {"fileid":"{fileId}"},
        {"siteUrl":"{siteUrl}"},
        {"key":"{apiToken}"},
        {"datasetid":"{datasetId}"},
        {"datasetversion":"{datasetVersion}"},
        {"locale":"{localeCode}"}
      ]
    },
  "requirements": {
    "auxFilesExist": [
      {
        "formatTag": "NcML",
        "formatVersion": "0.1"
      }
    ]
  },
  "contentType":"application/x-hdf5"
}'
```

Thanks!

**Comment by landreev** [comment]
BTW, this has been done - but I'll wait for somebody to check on it and confirm that it's all working they way it should be.

**Comment by pdurbin** [comment]
https://demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/JTUS2J/K68IDV&version=1.0 is looking good! Screenshot below.

![Screen Shot 2023-02-27 at 4 37 39 PM](https://user-images.githubusercontent.com/21006/221692228-c6e28641-ce5a-4c1d-8c15-e258533c05ad.png)

https://dataverse.harvard.edu/file.xhtml?fileId=6938801&datasetVersionId=340765 is also looking good. Screenshot below.

![Screen Shot 2023-02-27 at 4 41 38 PM](https://user-images.githubusercontent.com/21006/221692222-2029d055-ca9f-4bc5-94a1-72b77736e91a.png)

Those are both HDF5. I couldn't find any NetCDF files so I uploaded one to https://demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/UEMPZA/YFBGVG&version=1.0 and it looks good after publishing...

![Screen Shot 2023-02-27 at 4 45 40 PM](https://user-images.githubusercontent.com/21006/221693058-01ed6a83-108f-4402-a047-16cb4cc511a9.png)

... but before publishing I got a weird error about my API key. Not sure what's going on. I created another dataset on demo so I can see it:

"Unable to retrieve NcML file. Please try again. The most common issue is that your login has timed out. If the problem persists, please contact the support team of this data repository. Please include any status code included at the end of this message: Forbidden"

A screenshot for context:

![Screen Shot 2023-02-27 at 4 48 13 PM](https://user-images.githubusercontent.com/21006/221693399-e18ececd-197e-431f-b130-7eafb405f900.png)

I get the same error for an HDF5 file when it's in draft:

![Screen Shot 2023-02-27 at 4 49 16 PM](https://user-images.githubusercontent.com/21006/221693738-8a588dbb-d05a-409b-b58f-45e259f62dbe.png)

Again. I'm not sure what's going on but I'll ask around. If there's code to fix we can open a new issue and close this one. It seems like the tools were added just fine. Thanks, @landreev!

**Comment by landreev** [comment]
Let's take a closer look at the browser console log and confirm where the 403 is coming from - from Dataverse, or from aws, i.e. the redirect destination.

**Comment by landreev** [comment]
So, ok to close this? If there is a problem with the api token, sounds like it should be a simple fix on the tool side.

**Comment by pdurbin** [comment]
Yep, closing. I opened an issue to fix it:

- https://github.com/gdcc/dataverse-previewers/issues/25
