### ISSUE TITLE
Revive the handlenet server (for the legacy identifiers of the older studies in prod.)

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#215]
This service was running quietly for years on a dedicated server at LTS (dvn-handlenet.lib.harvard.edu; it had to be left there when the prod. cluster was moved to AWS, for some technical reasons I don't remember exactly). It was a very ancient setup that has been essentially frozen since we stopped registering new handles (meaning, years ago). It appears to have finally died - it stopped running and LTS have not been able to restart it, with mostly unhelpful messages in the logs. 
It may have become incompatible with the latest Java updates (it was running under 1.8.0, which is still being maintained and updated, remarkably). Or died for some other reason... basically we are being forced to finally upgrade the service; and, I'm assuming, re-register all those legacy handles. 

The practical impact of this is that some of the legacy handles are not resolving at the moment. I learned about this when I started receiving complaints (the latest one: 1902.1/22584) - people report these failures to handlenet, and they are automatically forwarding them to me. Hopefully not many people are still relying on these. But I am going to contact all the users who reported their handles not resolving and point them at the new DOIs for their datasets and tell them we are working on restoring the service. 

I'll need to read up on how to do all this/otherwise refresh my knowledge of all things handlenet. It's been a while.

**Comment by landreev** [comment]
I don't have shell access to the server, but got a tarred archive of the entire handlenet installation from LTS. Looking at it confirmed my worst fears, the whole thing is ancient - the timestamps on the jar files are from 2007! That version is 100% not supported anymore, and I'm surprised it was running all this time. 
In order to restore the service we likely need to install a new version of handlenet, then repopulate it from scratch by re-registering all the handle identifiers in prod. (I'll verify if this is no simpler way).

**Comment by rtreacy** [comment]
You should probably be able to run the upgrade procedures detailed here - http://www.handle.net/tech_manual/HN_Tech_Manual_9.pdf
You can seek guidance from handle-info@cnri.reston.va.us

**Comment by landreev** [comment]
I tried that first of course. It didn't work off the bat (due to some inconsistency in the old database; plus I don't think they ever expected that anyone would be upgrading from a version that ancient and all the way to the latest). 
But I did figure it out eventually.

**Comment by landreev** [comment]
To confirm what I said during the standup, the service is up now, the redirects are working (for example, https://hdl.handle.net/1902.1/11389 is properly redirecting to https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/11389). 
I need to finalize the new config, specifically the startup files, and then I'll move the issue forward.

**Comment by landreev** [comment]
Per conversation during standup yesterday, I'm moving this to "review" following our standard process. I'm assuming we just want to close this issue, now that the legacy handles are working and we can, hopefully, leave the service running in LTS care for another decade or so.

**Comment by landreev** [comment]
(I meant to close this issue last week - closing now)
