### ISSUE TITLE
Investigate why MORU metadatablock is preventing creation of datasets in the MORU collection

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#226]
The MORU metadatablock is preventing the saving of datasets in the MORU collection (https://dataverse.harvard.edu/dataverse/MORU). The error message in the UI doesn't tell us why:

![unnamed](https://github.com/IQSS/dataverse.harvard.edu/assets/18374574/79388516-9f29-40f9-8cb7-4b7d36467b7c)

But when I disable the metadatablock, so that its fields aren't included on the dataset create page, I'm able to save datasets.

The managers of the collection would like to start publishing datasets within the next two weeks. They've suggested creating the datasets without using the fields in the MORU metadatablock, and then editing the datasets to add metadata in those new fields once the change described in https://github.com/IQSS/dataverse.harvard.edu/issues/224 is made and they're able to save datasets that use these fields.

**Comment by landreev** [comment]
So, we still don't know why it's bombing when this block is enabled - I thought it was something straightforward, like another field needed to be changed in the block. 
Will take a look tomorrow. Hopefully there are some useful error messages in the server log to figure out what it doesn't like.

**Comment by qqmyers** [comment]
Has the solr schema been updated with the new custom fields for this block?

**Comment by landreev** [comment]
@qqmyers That's exactly what happened. It did get updated, but then got overwritten. I realized that this must have been the case at a random late hour last night. 
@jggautier I was able to save a dataset with some MORU fields just now, but please confirm.
