### ISSUE TITLE
Upgrade prod. servers to v6.0

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#229]
This is going to be a labor-intensive upgrade, on account of all the new components. 
I'm going to start working on preparing the servers and installing the new versions of the jdk/payara/solr etc. in parallel to the old infrastructure still running, to minimize the downtime as much as possible. I should get an idea in the process of roughly how long the downtime is going to be, then we can schedule it and give our users an early heads-up and give them a good idea of how much disruption to expect. 

We will have to do a full, from-scratch reindex - so we will need to warn everybody in advance that it will take a few hours to re-populate the bulk of the search catalogue.

**Comment by scolapasta** [comment]
6.0 deployed to Harvard Dataverse on the 10th of October.
