### ISSUE TITLE
HDF5 files show type "unknown"

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse.harvard.edu#23]
Noticed on https://dataverse.harvard.edu/file.xhtml?fileId=3052745&version=RELEASED&version=.0.
HDF5 is a reasonably widely used file format (https://www.hdfgroup.org/HDF5/)

**Comment by landreev** [comment]
The new type identification method caught 891 previously unrecognized files with the filename extension 'h5'. They have been re-typed as "application/x-h5". All future uploads of this file type will be properly identified automatically.
