### ISSUE TITLE
Create metadata blocks for CAFE's collection of climate and geospatial data

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#232]
This GitHub issue is being used to track progress of the creation of a metadata block or metadata blocks I'm helping design for a Dataverse collection that the [BUSPH-HSPH Climate Change and Health Research Coordinating Center (CAFE)](https://sites.bu.edu/climateandhealth/cafe) will be managing on Harvard Dataverse. Their unpublished collection is at https://dataverse.harvard.edu/dataverse/cafe.

In this repo at https://github.com/IQSS/dataverse.harvard.edu/tree/master/metadatablocks, I've added the .tsv and .properties files that define the metadata fields, and I'll continue updating those files as the CAFE folks review and improve the metadata fields.

_This screenshot shows the metadata block we're planning to add, as of 2023-11-07, so that depositors can describe the geospatial data:_
![cafedatalocation](https://github.com/IQSS/dataverse.harvard.edu/assets/18374574/2876bd5c-7d26-49fd-8d5a-fcbdb62e16bf)

_This screenshot shows the metadata block we're planning to add, as of 2023-11-07, so that depositors can describe the source datasets of the dataset being deposited:_
![cafedatasources](https://github.com/IQSS/dataverse.harvard.edu/assets/18374574/502aa68d-65ea-4215-9053-3d77c00084a0)

**Comment by jggautier** [comment]
**Concerns/risks**
I'd also like to use this GitHub issue to record the concerns/risks with this effort, similar to how we noted in other GitHub issues that metadata fields created for other collections in HDV serve purposes that overlap with fields already available (such as fields in the Citation metadata block) and facilitate describing data that others in the community have expressed interest in, like the metadata block for 3D Data discussed in https://github.com/IQSS/dataverse.harvard.edu/issues/144.

I spoke with the collection administrators about how the metadata added in these new metadata blocks won't be included in most metadata exports and won't be used to make the datasets more discoverable in other systems. This is the case with all "custom" metadata blocks we've added for collections in Harvard Dataverse.

We talked about how Dataverse has no way to show or hide fields based on what's entered in other fields, which is what they wanted to do for the first field in both metadata blocks. Those fields are dropdown menus where the options are "Yes" and "No". So if a depositor chooses "No" for the "Geospatial File Type" field, depositors shouldn't enter metadata in the other fields that describe the geospatial file, since there isn't one.

Similarly, we talked about how if depositors want to enter their own term for fields that include a vocabulary, such as the "Spatial File Type" field, they'll need to choose the dropdown menu's "Other" option, and type their term in the "Other Spatial File Type" field. We've used this pattern in the Life Sciences metadata block and other custom metadata blocks in HDV. The external controlled vocabulary mechanism handles this by using a UI component that let's depositors choose a term from a vocabulary and enter their own terms in the same field, but this mechanism works only for vocabularies hosted externally and not for vocabularies that are defined in metadata block TSV files.

_This screenshot shows the metadata block we're adding so that depositors can describe the geospatial data:_
![cafedatalocation](https://github.com/IQSS/dataverse.harvard.edu/assets/18374574/2876bd5c-7d26-49fd-8d5a-fcbdb62e16bf)
The collection's administrators wanted to include these fields in the geospatial metadata block that ships with Dataverse. Because it would take more time than they have to do that, we agreed to create this new metadata block for the CAFE collection, instead. They're interested in joining the Dataverse community's discussions about improving how depositors describe geospatial data and I'll need to connect them with @pdurbin and others who've worked on this.

Collection administrators expect that each deposit will include only one geospatial file, which these fields describe. This use case has been listed among use-cases being collected to support the need for improving Dataverse's ability to record file-level metadata.

_This screenshot shows the metadata block we're adding so that depositors can describe the source datasets of the dataset being deposited:_
![cafedatasources](https://github.com/IQSS/dataverse.harvard.edu/assets/18374574/502aa68d-65ea-4215-9053-3d77c00084a0)
We talked about how the fields overlap with the "Related Dataset" and "Data Source" fields and that once Dataverse can send metadata about related resources to DataCite (https://github.com/IQSS/dataverse/issues/5277), we'll need to think about if and how to include the related datasets described in the fields in this custom metadata block.

We talked about how when the metadata is displayed on the dataset page, it's hard to read. This is discussed more in  https://github.com/IQSS/dataverse/issues/6589.

We talked about how the automatic layout of the child fields might confuse depositors. For example, depositors need to see the relationship between the "Type" and "Other Type" fields, since depositors are asked to use the "Other Type" field to add a term that isn't in the list of terms in the "Type" dropdown. But these fields are on separate lines. We've seen and talked about how this issue confuses depositors using other compound fields like the Related Publication fields.

**Comment by cmbz** [comment]
**2023/11/13**
- After discussion during the prioritization meeting, I added to Global Backlog in the new NIH CAFE Project column. 
- Will be completed during 6.1 timeframe (note, this is a Harvard Dataverse installation improvement)
- Possibly assign to @stevenwinship once the issue has been sized 
- Next step: Move into Needs Sizing, then Sprint Ready for final 6.1 sprint.

**Comment by landreev** [comment]
@jggautier Just to confirm - am I installing both customCAFEDataLocation.tsv and customCAFEDataSources.tsv in prod.?

**Comment by jggautier** [comment]
Ah yes. That CAFE collection's managers would like both of those metadata blocks available for the collection. I'll update this issue's title.

**Comment by landreev** [comment]
I looked into this briefly, and I'm wondering if it would be better for new blocks to go through more of a qa process, like with do with everything else, before deploying them in prod. 
My biggest questions/concern were with the GeoSpatialResolution fields in these blocks, since we just had to spend so much effort addressing issues with similar fields in the Geospatial block. 
There may be some similar issues with validation for the values in this block. Namely, the values are defined as floats. So it is impossible to enter anything that does not parse as a decimal fractional. This would be the right behavior when "Decimal degrees" is selected in the "Unit" pulldown. But you can also select “Degrees-minutes-seconds” in the same pulldown - but it is then impossible to enter such a value: 
![Screen Shot 2023-12-14 at 12 06 43 PM](https://github.com/IQSS/dataverse.harvard.edu/assets/737558/c3bdd03c-099d-48c1-91ee-dcad8f7f2e71)
(there are other notations for formatting "degrees-minutes-seconds" values of course, but none of them will parse as a valid decimal fractional). 
I feel like if we want this field to support all the notations listed, the only way to achieve that would be to switch it back to text, and add custom validation methods, like we did with the Geospatial block fields.

**Comment by landreev** [comment]
I was also told that there were some technical issues with bringing up a test instance for the researchers involved to experiment with. But I feel like that part must be something we can figure out.

**Comment by jggautier** [comment]
@sbarbosadataverse, it was agreed to continue testing this and the other metadata block after they were added to Harvard Dataverse.

But can we bring up this concern, about validation, with the collection's manager Keith, and ask if user testing can be done before these metadatablocks are added?

**Comment by landreev** [comment]
We had a quick chat about this on slack. It sounded like I should clarify what I said above: 
> like we do with everything else, before deploying them in prod.

By "like we do with everything else" I didn't meant literally the same process as how we QA dev. issues - deploying it on dataverse-internal, have the same QA person test it, etc. etc. I meant more like the same idea of testing and confirming that everything works properly before trying it in prod. It sounds like this should be a somewhat different process for custom blocks - focused more on letting the researchers who requested the block do the testing and confirming that everything works the way they like.

**Comment by landreev** [comment]
> @sbarbosadataverse, it was agreed to continue testing this and the other metadata block after they were added to Harvard Dataverse.
> 
> But can we bring up this concern, about validation, with the collection's manager Keith, and ask if user testing can be done before these metadatablocks are added?

Basically, rather than using the production for testing these blocks, let's let the collection admin(s) experiment with them on a test instance.

**Comment by jggautier** [comment]
A Dataverse instance was spun up with the metadatablocks (thanks @landreev!) and I gave the collection manager the URL so that he can review the fields and the concerns that Leonid brought up and potentially review with others who will be helping manage or deposit data in the collection.

There's a question about if it's possible to create the instance with https so that things entered in the site are secure. It's possible they thought they'd have to log in or create an account using the same credentials they use on Harvard Dataverse. I'm waiting to learn more about why it's needed and if it's possible or worth the trouble.

We'll probably pick this up next week.

**Comment by jggautier** [comment]
Nevermind about the creating the test instance with https instead of http. The repository manager was able to create an account and review the new fields.

We're emailing this week about changes to a few of the fields and I'll describe those as the work ramps back up after the holiday break.

**Comment by landreev** [comment]
OK, please let me know if you need anything else from me and/or if the block is ready to be installed in prod.

**Comment by jggautier** [comment]
Thanks. I just updated the customCAFE files in [the metadatablocks directory of this repo](https://github.com/IQSS/dataverse.harvard.edu/tree/master/metadatablocks).

I haven't been able to see if the changes I made today to the TSV and .properties files results in what the collection admin and we expect to see in the UI (since I haven't been able to spin up branches with custom metadata blocks on AWS and more recently started seeing error messages that prevent me from creating a local instance using Docker).

Could you install both metadata blocks on Harvard Dataverse when you have time? Then I'd let the collection admin to make sure everything is working as expected before they start creating datasets.

**Comment by landreev** [comment]
I'll install the blocks and confirm. 
I haven't read everything above, yet (sorry), but I noticed this: 

> I haven't been able to see if the changes I've made to the TSV and .properties files result in ... since I haven't been able to spin up branches with custom metadata blocks on AWS 

Is the test instance that we configured earlier still running the old version of the block? All you need to do to update the block is log in there and update the block on the command line. 3 commands max., if the solr schema update is needed. I could do that too. 

If you ever need to test another block, that should be the easiest way to go - just spin up the master or default branch with the default settings, then log in and install the block once it's running.

**Comment by jggautier** [comment]
Thanks, yeah, a while back I tried to follow the steps in [the guides about updating metadata blocks](https://guides.dataverse.org/en/6.0/admin/metadatacustomization.html#reloading-a-metadata-block), I failed, and I spoke a bit with Don Sizemore. He tried to help, but I wasn't able to update a metadata block on the test instance on AWS, I wasn't sure why, and I mostly ran out of time trying to troubleshoot. I can try again next time. And if I run into trouble again, hopefully I can ask how you did it?

**Comment by landreev** [comment]
> if I run into trouble again, hopefully I can ask how you did it? 
Sure, of course.

**Comment by landreev** [comment]
The updated blocks have been installed. Please let me know if there are any problems.

**Comment by landreev** [comment]
OK. Also, let me know if you need me to update the blocks the test instance.

**Comment by jggautier** [comment]
Thanks yeah I agree it would be better to be able to as much reviewing as possible on the test instance.

After I heard in standup yesterday about improvements to the AWS instances, I thought I'd try to update the metadata fields on that test instance today.

Mind if I try again today?

I could let you know if I run into issues, and then it'll probably be easier if you just do it.

**Comment by jggautier** [comment]
Hey @landreev. I'm remembering more about why it was tough for me to try to update metadata blocks in AWS instances. I think I need to update one of the .properties files as well as both TSV files, and the steps at https://guides.dataverse.org/en/6.1/admin/metadatacustomization.html#reloading-a-metadata-block don't mention the .properties files, so I'm not sure what to do for that.

Could you update the CAFE metadata blocks in [the test instance](http://ec2-3-90-138-69.compute-1.amazonaws.com/)? I updated both TSV files and one of the .properties files (customCAFEDataLocation.properties).

**Comment by landreev** [comment]
Adding the update commands here just in case: 

scp customCAFEData* to /tmp (for example) on the destination system; 
scp this script there as well: https://raw.githubusercontent.com/IQSS/dataverse/master/conf/solr/9.3.0/update-fields.sh

There, on the command line: 
```
cd /tmp
curl http://localhost:8080/api/admin/datasetfield/load -H -type: text/tab-separated-values" -X POST --upload-file customCAFEDataLocation.tsv
(repeat for the other .tsv file)
sudo cp /tmp/customCAFEData*.properties /usr/local/payara6/glassfish/domains/domain1/applications/dataverse/WEB-INF/classes/propertyFiles/
```

Solr schema update (idk if the changes you've made actually require solr schema update - probably not? - but this would need to be done when installing a new block)

```
sudo service solr stop
curl "http://localhost:8080/api/admin/index/solr/schema" | sudo /tmp/update-fields.sh /usr/local/solr/server/solr/collection1/conf/schema.xml
sudo service solr start
```

**Comment by jggautier** [comment]
Oh great, thanks for the commands @landreev. After reviewing, there's another fix I need to make. I'd like to try these commands to update customCAFEDataSources.tsv. But I see that a few of the changes I made the last time aren't reflected on the test instance, and I'm not sure how to avoid this if I try to make these changes. 

For example, the "Geospatial File Type" field should have been replaced by "Includes a Geospatial File," but both files exist on the test instance. And I meant to remove validation from the Spatial Resolution Value field, but it still expects a number. Here's a screenshot showing what I mean.

<img width="941" alt="Screenshot 2024-01-16 at 9 10 23 AM" src="https://github.com/IQSS/dataverse.harvard.edu/assets/18374574/b3aa3a80-f557-4593-907e-0db148465af3">

Something similar happened with the customCAFEDataSources metadata block.

I changed the database names of some fields in both metadata blocks. Could that be part of the issue?

<img width="998" alt="Screenshot 2024-01-16 at 9 03 33 AM" src="https://github.com/IQSS/dataverse.harvard.edu/assets/18374574/1e2f9926-9dd2-4ec6-9f7b-c0a9bc63f787">

And many of the fields I meant to rename in this customCAFEDataSources metadata block are still the same name. For example, "Title" should be "Source Dataset Title". I appended "Source Dataset" to many of these fields.

Lastly and unfortunately, in the [CAFE collection](https://dataverse.harvard.edu/dataverse/CAFE) on Harvard Dataverse where we added the metadata blocks, two datasets were published today that use the new fields, and some of these fields are the fields that need to be fixed. I disabled the two metadata blocks, told the collection admin that I disabled them, and let the admin know that the fields shouldn't be used until we can update them. The two published datasets are at https://doi.org/10.7910/DVN/Y1WNU7 and https://doi.org/10.7910/DVN/HYNJSZ.

So after we're done reviewing the metadata blocks, and update the metadata blocks that are on Harvard Dataverse, will something need to be done to fix the metadata of the these two published datasets?

**Comment by landreev** [comment]
I didn't restart the application on the test instance after updating the block; I thought it wasn't necessary, but let me do that now. 
That said, the `cafeSpatialResolutionValue` in your updated `customCAFEDataLocation.tsv` is still a `float`:
`	cafeSpatialResolutionValue	Value	The number value indicating the horizontal grid spacing of the raster data (e.g. "30" for 30 meter x 30 meter gridded data)		float	7	#NAME: #VALUE	TRUE	FALSE	FALSE	TRUE	TRUE	FALSE	cafeSpatialResolution	customCAFEDataLocation`
so this is the correct behavior, that it's still validated as a number. (I assumed that was what you wanted though - since the "degrees-minutes-seconds" was removed from the list of supported units, and all the other units do have to be numbers.

**Comment by landreev** [comment]
Please try again now?

**Comment by landreev** [comment]
... still looks wrong - ?

**Comment by jggautier** [comment]
I tried again, refreshing the page and trying different browsers, but yeah it does look wrong. Maybe we could talk with some screen sharing later today (on a Slack huddle or over Zoom)?

**Comment by landreev** [comment]
Did you say you changed some of the database names of the fields? (as opposed to the descriptive labels shown in the UI)

**Comment by jggautier** [comment]
Yeah, I changed the database names of some of the fields.

**Comment by landreev** [comment]
Could be a reason these fields are not updated - the update mechanism is based on matching the fields by name. (?)
Let me try erasing the blocks and reinstalling again, instead of updating.

**Comment by landreev** [comment]
Please take a look now?

**Comment by jggautier** [comment]
Thanks! That worked!

Here are the remaining issues:

1. In the "Metadata About Data Location" metadata block, the Spatial Resolution Units field is missing because I used the wrong database name when I updated customCAFEDataLocation.tsv. This is the field that should have the controlled vocab with the dropdown menu of units (where we removed "degrees-minutes-seconds").
2. The label for the cafeSpatialReferenceSystem field should be renamed from "Spatial Reference System Name" to "Spatial Reference System".
3. About the field validation, for the cafeSpatialResolutionValue field I meant to use the "text" field type, but like you wrote it's still float. A couple of weeks ago [I wrote](https://github.com/IQSS/dataverse.harvard.edu/issues/232#issuecomment-1875944521) that we'd remove the validation altogether, but since you think the validation makes sense because we removed "degrees-minutes-seconds" from the options in the cafeSourceDataSpatialResolutionUnit field, I'll change the Spatial Resolution Unit field in the other metadata block (customCAFEDataSources.tsv), so that it expects a float, too, and I'll  let the collection admin know that we'll make sure that the Spatial Resolution Unit fields in both metadata blocks expect floats.

I updated the TSV files and the customCAFEDataLocation.properties in [this repo's metadatablock directory](https://github.com/IQSS/dataverse.harvard.edu/tree/master/metadatablocks) and I'll email the collection admin now about the float field validation.

If he's okay with the validation, too, then:

- Could you erase the blocks and reinstall them again? Or I can try to erase the blocks and reinstall them again, or I could try to create a new test instance and shutdown the one we're using now, which I think I know how to do.
- I wrote about the two published datasets that have already used these new fields (https://doi.org/10.7910/DVN/Y1WNU7 and https://doi.org/10.7910/DVN/HYNJSZ). I think that only the dataset at https://doi.org/10.7910/DVN/Y1WNU7 uses a field that needs to change: "Source Dataset Title" is required but shouldn't be. I'm not sure if, after the metadata blocks on Harvard Dataverse are updated, anything else needs to be done about the metadata in these two datasets.

**Comment by landreev** [comment]
The block update commands above should work, but apparently only if no database names are changed. 
There's no clean way to uninstall a block. I did it with database queries; going forward, the recommended way should probably be to junk the instance and spin up a new one. 
I don't mind erasing and reinstalling this block on this instance though, just let me know when.

**Comment by jggautier** [comment]
Hey @landreev. The collection admin said the values should always be floats, so the validation is fine.

I just updated the TSV and .properties files in [this repo's metadatablock directory](https://github.com/IQSS/dataverse.harvard.edu/tree/master/metadatablocks).

Could you erase and reinstall the two metadata blocks on [the test instance](http://ec2-3-90-138-69.compute-1.amazonaws.com/) today?

**Comment by landreev** [comment]
OK, will do.

**Comment by landreev** [comment]
Should be done now.

**Comment by jggautier** [comment]
I see it. Thanks!

**Comment by cmbz** [comment]
2024/01/17: resized at 10 during kickoff.

**Comment by jggautier** [comment]
I made more small changes (field labels and display formats) to the both metadata blocks. The TSV and .properties files in [this repo's metadatablock directory](https://github.com/IQSS/dataverse.harvard.edu/tree/master/metadatablocks) are updated and I think are ready to be added to the CAFE collection in Harvard Dataverse.

You wrote that to deal with the already published datasets in the CAFE collection, you might have to erase all the existing fields associated with the new fields in the two metadata blocks and then have them re-enter the fields once the updated blocks are reinstalled.

About the two published datasets that are using fields in the metadata blocks, you wrote:
> Trying to think of how to deal with the already published dataset(s) in prod. using these blocks. I don't think there's any other way than to erase all the existing fields associated with [the metadata blocks]; then have [the depositors or curators] re-enter the fields once the updated blocks are reinstalled.

Does that mean that the datasets would be taken back to an unpublished state? I'm trying to think about what we should let the collection admin know.

**Comment by landreev** [comment]
> Does that mean that the datasets would be taken back to an unpublished state? 

I was thinking of removing all the CAFE* fields from the 2 datasets, but leaving them published with the other metadata values intact. Then, once the fixed blocks are installed, they would edit and republish them as needed. 

If it's necessary to revert them to unpublished drafts, that can be done as well. We are already doing so many hacky/custom things for this effort, might as well. 

But it is necessary to remove ALL the existing CAFE fields; not just the ones that have been modified. Because we need to uninstall the blocks before we can install the fixed versions.

**Comment by jggautier** [comment]
Ah, I get it. I can't imagine that the collection admin would object to having to create a new minor version for each dataset. so hopefully we don't have to revert the published datasets back to unpublished drafts.

I'll email the collection admin now to ask.

**Comment by landreev** [comment]
These latest block changes, do they need to be applied on the test ec2 instance?

**Comment by qqmyers** [comment]
@jggautier FWIW: Update-current-version could also be done to avoid a new version (with appropriate permissions).

**Comment by jggautier** [comment]
Yes, could you apply the latest block changes to the test ec2 instance @landreev?

**Comment by landreev** [comment]
@qqmyers that was my *optimistic* plan - to remove the populated fields belonging to the blocks in the UI, then use update-current-version on the resulting drafts. 
That luxury may be out of our reach tough. Some of these fields are required, and even though the blocks are no longer enabled on the parent collection, I'm not sure if it's possible to erase them using the UI. But I'll find out soon. 

If not, then removing them with database queries it'll be... But, no drafts to worry about.

**Comment by landreev** [comment]
@qqmyers Oh, you were talking about skipping extra published versions once they add the fields. Got it now, sorry.

**Comment by jggautier** [comment]
Thanks @landreev for applying the changes to the ec2 test instance! I see the changes and everything's working as expected.

I'll let the collection admin know that:
- We'll remove and re-add the metadata blocks on their collection in Harvard Dataverse
- For those two datasets that had already used the new metadata fields, we'll have to remove the fields, they'll have to re-enter the metadata once the metadata blocks are re-added, save their metadata changes, and let us know so that one of us can use a super-user account to publish the changes without creating new versions.

Does that all sound good? I'll wait to hear back from you before I email the collection admin.

**Comment by jggautier** [comment]
Okay, they wrote that they're okay with it

**Comment by landreev** [comment]
OK, I'll look into the 2 datasets with the populated fields next. Will report.

**Comment by landreev** [comment]
For the record - nope, you cannot remove these CAFE*-blocks fields in the UI. ☹️ On account some of them being required. 
We will need to resort to some hackery to resolve this. I need to be super careful about it, so it may take some appreciable time.

**Comment by landreev** [comment]
Looking into it now.

**Comment by landreev** [comment]
@jggautier Could you please confirm that these are the versions of the blocks that are currently installed in production? (Jan. 3 commits) - 

https://github.com/IQSS/dataverse.harvard.edu/blob/f4a79a733a9d5b816080cf463914e8743a761fff/metadatablocks/customCAFEDataLocation.tsv
and 
https://github.com/IQSS/dataverse.harvard.edu/blob/f4a79a733a9d5b816080cf463914e8743a761fff/metadatablocks/customCAFEDataSources.tsv

Not super crucial; I just want to replicate the prod. setup on my own dev. box 1:1 to test the delete queries.

**Comment by landreev** [comment]
successfully removed "Location"...
"Sources" next...

**Comment by landreev** [comment]
OK, all the existing field values and fields have been erased, and both custom blocks uninstalled, like they were never there. 
I will install the new versions later tonight (so that I don't have to restart Solr during the day). 
If you have a sec., please take a look at the 2 published datasets in question, just to confirm that there's nothing visibly wrong with them after I had to mess with the metadata in the database. Just in case, I'm fairly positive they should be ok. 🤞

**Comment by landreev** [comment]
(no, I didn't get to installing the blocks last night, but will do shortly)

**Comment by jggautier** [comment]
Thanks. Sorry I didn't get to help [look at those Jan. 3 commits yesterday](https://github.com/IQSS/dataverse.harvard.edu/issues/232#issuecomment-1908782928). Got caught up in other stuff.

I checked those two published datasets. They're editable and I don't see any traces of the new blocks' fields in the forms.

I do see the metadata in the JSON exports, like https://dataverse.harvard.edu/api/datasets/export?exporter=dataverse_json&persistentId=doi:10.7910/DVN/Y1WNU7. Just pointing that out just in case.

**Comment by landreev** [comment]
Correct, I didn't bother re-exporting the 2 datasets. 
They will be automatically re-exported when they are re-published.

**Comment by landreev** [comment]
The 2 blocks have been installed (again). Please review/double-check that these are the correct versions.

**Comment by jggautier** [comment]
I just reviewed them and they're the correct versions. Thanks!

**Comment by landreev** [comment]
@jggautier Can we close it, or do you want to keep it open until they enter all the metadata they need?

**Comment by jggautier** [comment]
Ah, yes we can close it. I'll do that now. Wasn't sure if there was anything else we needed to do for re-adding the metadata blocks.

We can track the remaining tasks, mostly about those two published datasets you edited, in our email thread with the collection admin.
