### ISSUE TITLE
What would Data INRA like Harvard Dataverse to harvest?

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#236]
The harvesting job that used to harvest metadata into the collection at https://dataverse.harvard.edu/dataverse/inra_harvested has been failing for a while. It's one of several failing jobs. See https://github.com/IQSS/dataverse.harvard.edu/issues/92.

So clicking on the title of each dataset no longer leads to the dataset but to a 404 page, and Harvard Dataverse hasn't been updating the metadata it's harvested.

The installation's URL, https://data.inra.fr, now redirects to https://entrepot.recherche.data.gouv.fr/dataverse/inrae. Dimitri Szabo let us know about this and we updated the Dataverse map (https://github.com/IQSS/dataverse-installations/pull/162), but we didn't adjust the harvesting job settings, which are still trying to use the OAI-PMH endpoint https://data.inra.fr/oai, which isn't working anymore.

We might need to update the settings so that Harvard Dataverse is harvesting from https://entrepot.recherche.data.gouv.fr/oai instead, and possibly adjust the URL, name and description of the collection at https://dataverse.harvard.edu/dataverse/inra_harvested depending on what the folks from INRAE would like Harvard Dataverse to harvest.

Their harvesting sets are listed at https://entrepot.recherche.data.gouv.fr/oai?verb=ListSets and the list includes a set called INRAE. Who ever works on this issue might ask Dimitri Szabo (dimitri.szabo@inrae.fr) about what they'd like Harvard Dataverse to harvest, then adjust the settings to re-harvest their metadata and ensure that it stays up to date.

**Comment by pdurbin** [comment]
I sent @DS-INRA (Dimitri) a link to this issue.

**Comment by DS-INRA** [comment]
Hello, reacting only today, thanks for raising the issue !
Please use the set `ALL` instead of INRAE from  https://entrepot.recherche.data.gouv.fr/oai as other organizations are now also in the repository :) .

**Comment by jggautier** [comment]
Perfect. Thanks @DS-INRA! We'll use that set then.

I'll change the name of the collection at https://dataverse.harvard.edu/dataverse/inra_harvested, to "Recherche Data Gouv Harvested Dataverse", the URL to https://dataverse.harvard.edu/dataverse/recherchedatagouv, and I'll remove the description.

Let me know if you'd like any done differently with those things changed, too.

**Comment by jggautier** [comment]
Client was deleted 🎉, and records in the ALL set of https://entrepot.recherche.data.gouv.fr/oai are being harvested into https://dataverse.harvard.edu/dataverse/recherchedatagouv. I'll close this issue and open another any issues come up. 

Thanks @DS-INRA!

**Comment by DS-INRA** [comment]
Great, many thanks !

**Comment by jggautier** [comment]
Just an update here. 37 records were harvested into https://dataverse.harvard.edu/dataverse/recherchedatagouv and Dataverse reports that it couldn't harvest 2325 records.

I'll update the issue at https://github.com/IQSS/dataverse.harvard.edu/issues/92, where I've been writing about failing harvests.

**Comment by DS-INRA** [comment]
> I'll update the issue at #92, where I've been writing about failing harvests.

Thanks, feel free to tag me there so that I don't miss it!

**Comment by pdurbin** [comment]
@DS-INRA you can also click "subscribe" on the issue.

**Comment by jggautier** [comment]
@DS-INRA, https://github.com/IQSS/dataverse.harvard.edu/issues/92 was closed instead, a few months after [I left that comment about updating that Github issue](https://github.com/IQSS/dataverse.harvard.edu/issues/236#issuecomment-1850302966). So I don't think you need to subscribe to it.

Harvard Dataverse has still harvested just 37 records from Recherche Data Gouv and has since stopped harvesting from all repositories it used to in order to address indexing-related issues that were affecting how well it harvests.

But eventually we'll keep looking into cases where Harvard Dataverse isn't harvesting well or at all from certain repositories and we'll ping you.
