### ISSUE TITLE
Deploy release 6.1 in HDV 

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#239]
Early next week, probably (?).

**Comment by landreev** [comment]
We could deploy this week if it was really urgent. My only reservation is that I had a bit of a scare last week when I was having some trouble deploying 6.1 on our "performance cluster" test system, that uses a copy of our production database. I was just hoping to do a bit more testing to confirm that there's nothing in our prod. data that can cause intermittent deployment errors (I was eventually able to deploy; but still not sure what exactly was happening). 
I really don't want to get stuck like that during a real prod. deployment.

**Comment by cmbz** [comment]
@landreev I think that either sometime next sprint is fine. Better safe than sorry :)

**Comment by landreev** [comment]
gave it a (very generous) 10 - to count whatever prep may be necessary.

**Comment by cmbz** [comment]
Great, moving to Spring Ready now.

**Comment by landreev** [comment]
Put a "waiting" label on this one. Since that's precisely what I'm doing - waiting for patches to be ready that I could quickly build and deploy in our prod. (if not an official 6.1.1 mini-release).

**Comment by landreev** [comment]
Removed the "waiting" tag.

**Comment by landreev** [comment]
Deploying as I type this... (the release comes with one flyway database update that takes a while to execute - up to 20 min. on the prod. db clone - so, longer than usual downtime window has been requested; waiting for it to complete now).

**Comment by landreev** [comment]
Keeping it open a little longer, just in case.
