### ISSUE TITLE
Links on nav bar on User Guide page point to dead pages: Harvard Dataverse Policies, Replication Dataset Guidelines

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#24]
From the [User Guides page](http://guides.dataverse.org/en/4.15/user/), in the Best Practices dropdown, the links for **Harvard Dataverse Policies** and **Replication Dataset Guidelines** point to dead pages:

Harvard Dataverse Policies goes to https://dataverse.org/harvard-dataverse-policies. Should go to:
- https://dataverse.org/best-practices/harvard-dataverse-policies
- Or to http://best-practices.dataverse.org/harvard-policies/index.html if for some reason we need to keep using the version of the content created with Sphinx

Replication Dataset Guidelines goes to https://dataverse.org/replication-dataset. Should go to: - https://dataverse.org/best-practices/replication-dataset
- Or to http://best-practices.dataverse.org/replication.html if for some reason we need to keep using the version of the content created with Sphinx, although the content on that page is not quite the same - content on https://dataverse.org/best-practices/replication-dataset seems newer.

(The rest of the links in the User Guides nav bar point to the appropriate pages. The links in the nav bar on dataverse.org also all point to the appropriate pages.)

**Comment by pdurbin** [comment]
We want to take down http://best-practices.dataverse.org so we shouldn't link to it.

That's what this issue is about: Privacy Policy URL update on the Homepage #7

**Comment by jggautier** [comment]
But http://best-practices.dataverse.org was re-enabled so that the Privacy Policy page on it could be linked to. Why was that done instead of replacing the Privacy Policy URL with the one on dataverse.org?

**Comment by pdurbin** [comment]
@jggautier it was simply the fastest way to make sure the Privacy Policy on Harvard Dataverse didn't go to a dead link. #7 should be trivial to fix. Someone just needs to ssh into one of the production servers and change the `:ApplicationPrivacyPolicyUrl` setting. Then I can shut down http://best-practices.dataverse.org

I believe https://docs.google.com/spreadsheets/d/1YGWcMhGJZa7K1QBSJBc_B9J778sGV2UnG0RbooLmF-E/edit?usp=sharing is the spreadsheet we were looking at when we decided in February or so to kill the best practices site but I may be mistaken.

**Comment by pdurbin** [comment]
I just noticed this issue in Up Next and thought I'd mention that http://best-practices.dataverse.org is long gone. It used to be hosted on the same server as https://guides.dataverse.org (dvnweb-vm3.hmdc.harvard.edu) when it was hosted by IQSS. The guides have been hosted by GDCC/Odum (thanks, @donsizemore!) for a year or two. I'd say we can safely remove "best-practices" from DNS.

**Comment by jggautier** [comment]
Ah thanks. [The original post says](https://github.com/IQSS/dataverse.harvard.edu/issues/24#issue-466356651) that two links should be changed and points to links that are also now dead. Updating here:

From the [User Guides page](http://guides.dataverse.org/en/4.15/user/), in the Best Practices dropdown, the links for **Harvard Dataverse Policies** and **Replication Dataset Guidelines** point to dead pages:

- Harvard Dataverse Policies goes to https://dataverse.org/harvard-dataverse-policies. The page has been moved to the Harvard Dataverse Repository support website and is now at  https://support.dataverse.harvard.edu/policies.
- Replication Dataset Guidelines goes to https://dataverse.org/replication-dataset. Those guidelines are now at https://dataverse.org/best-practices/replication-dataset

(The rest of the links in the User Guides nav bar point to the appropriate pages. The links in the nav bar on dataverse.org also all point to the appropriate pages.)

**Comment by pdurbin** [comment]
Under "Best Practices" in the nav bar for the guides...

![Screen Shot 2022-03-15 at 10 04 36 AM](https://user-images.githubusercontent.com/21006/158395261-10cef650-d03d-4aa1-8a42-d61f4fbbd25b.png)

It makes complete sense to update "Replication Dataset Guidelines" to point to the working link at https://dataverse.org/best-practices/replication-dataset

However, should the "Harvard Dataverse Policies" link be deleted? I ask this because the impression I get from #65 is that we don't particularly want Harvard content on dataverse.org sites (such as guides.dataverse.org). Here's what that issue says:

> we need to edit content on dataverse.org so that it does not contain Harvard Dataverse information
