### ISSUE TITLE
Load updated custom CAFE metadata block (displayname changed from "Metadata About Data Location" to "Metadata About Geospatial Files") to demo and prod

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#244]
Our contact for the CAFE collection let us know that depositors found the name of the custom metadata block, "Metadata About Data Location", confusing, taking it to mean "metadata about where the data are stored," when it should be metadata about where the data was collected or what the data is about.

He asked us to change the name of the metadata block, that is, the "displayName" entered in the [metadata block's TSV file](https://github.com/IQSS/dataverse.harvard.edu/blob/master/metadatablocks/customCAFEDataLocation.tsv), to `Metadata About Geospatial Files`.

So in place of "Metadata About Data Location" in this panel on the dataset page:
<kbd><img width="1148" alt="Screenshot 2024-02-21 at 12 46 20 PM" src="https://github.com/IQSS/dataverse.harvard.edu/assets/18374574/c5a307bf-00ff-4fac-b039-8193ab121b38"></kbd>

It would be "Metadata About Geospatial Files".

**Comment by pdurbin** [comment]
@jggautier are you working on this? If not, I think @cmbz would agree that this could be a good issue for @Saixel.

I'm going to go ahead and give it a size of 3.

**Comment by pdurbin** [comment]
@jggautier sounds good. Please request a review from @Saixel after you make a pull request so he can see the change.

He won't have access to prod though. So getting it into prod should go through the normal process.

**Comment by jggautier** [comment]
Hmm, I haven't used pull requests in this repo. In the [customCAFEDataLocation.tsv](https://github.com/IQSS/dataverse.harvard.edu/commit/c6e8e378023de527734330ea87c4518e1ba0167a) and [customCAFEDataLocation.properties](https://github.com/IQSS/dataverse.harvard.edu/commit/4b7b7c3c7733320c3987fd3e58535189d2cd50f1) files I changed the displayName of the metadata block to "Metadata About Geospatial Files".

@Saixel, could you review of the history of those changes?

**Comment by pdurbin** [comment]
@Saixel please read through the following: https://guides.dataverse.org/en/6.1/admin/metadatacustomization.html#loading-tsv-files-into-a-dataverse-installation

Then, please load the older version of the tsv to observe the old display name.

Then, please load the newer version to make sure it changed.

This is all new to you, so please reach out in Slack with questions! Thanks!

**Comment by Saixel** [comment]
I've followed the discussed steps and conducted the necessary tests. I created the `customCAFEDataLocation.tsv` and `customCAFEDataLocation.tsv.properties` files based on @jggautier's modifications. I've tested the functionality as required, executing both the old version of the TSV file and then the new one to ensure that the name updates without any issues @pdurbin

**Comment by scolapasta** [comment]
OK, after reviewing with @jggautier and @Saixel, seems like the remaining step is to load these into demo and prod. So I'm going to retitle this for that remaining task, and move back to This Sprint.

Let's do demo firs,t have @jggautier or @Saixel check to make sure it looks correct, then load into prod.

**Comment by jggautier** [comment]
I think the idea was to put it on Demo Dataverse first so that @Saixel or I could make sure the change is what we expect. And if it is, then someone could load it into Harvard Dataverse.

I just checked and the change on Harvard Dataverse is what I expected, so I don't think it needs to be added to Demo Dataverse. Maybe that first step wasn't needed at all since it's a small change; not much context needed to make sure the change happened the way we expected and maybe it's easy to reverse if something went wrong?

**Comment by landreev** [comment]
Oh, sorry, I didn't get that. Yeah, since it was just a label, probably ok to skip the testing stage. 

Going forward, when a block is ready to be installed (in prod. or demo), feel free to just ping me on slack (or Steven if I'm not around). It really doesn't take any time at all.

**Comment by landreev** [comment]
OK to close this?

**Comment by jggautier** [comment]
Hmm, I'd say wait to hear from @Saixel. I think he's more aware of CAFE project-related things 👍

**Comment by landreev** [comment]
@jggautier ok if I put your name on this, so that you could close it once they confirm (or give it back to me if there are problems)?

**Comment by Saixel** [comment]
Everything okay, we can close this!
