### ISSUE TITLE
Install TurborCurator

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse.harvard.edu#245]
Install the TurborCurator tool on Harvard Dataverse and test its deployment in preparation for an announcement about its availability.

**Comment by landreev** [comment]
No problem, but please upload, or point me to, the json to import for the tool.

**Comment by landreev** [comment]
It should take a minute to activate in prod. It sounds like we should do this on Mon. morning - but please let me know otherwise.

**Comment by pdurbin** [comment]
The manifest is here: https://turbocurator.icpsr.umich.edu/tc/turbocurator_manifest.json

Via https://turbocurator.icpsr.umich.edu/tc/adminabout

Via https://preview.guides.gdcc.io/en/develop/admin/external-tools.html#inventory-of-external-tools (preview for now, will be in 6.2, see https://github.com/IQSS/dataverse/pull/10281 )

**Comment by landreev** [comment]
Installed in prod. last night (Sunday Feb. 11), please test and report.

**Comment by pdurbin** [comment]
@landreev thanks! I just tried it on my [Open Source at Harvard](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TJCLKP) dataset and it seemed to work fine:

<img width="1582" alt="Screenshot 2024-02-12 at 7 38 09 AM" src="https://github.com/IQSS/dataverse.harvard.edu/assets/21006/204f63cc-336d-43fe-829d-d226b3adb122">
<img width="1582" alt="Screenshot 2024-02-12 at 7 38 46 AM" src="https://github.com/IQSS/dataverse.harvard.edu/assets/21006/7140ddf1-10cc-4508-9161-f0922c8c260a">
<img width="1582" alt="Screenshot 2024-02-12 at 7 39 11 AM" src="https://github.com/IQSS/dataverse.harvard.edu/assets/21006/f8a54111-290f-4844-be52-fbd3f824e7d4">

**Comment by pdurbin** [comment]
Here's the announcement about TurboCurator: https://groups.google.com/g/dataverse-community/c/xH6N4sIUizU/m/DL1-l6iVAAAJ

**Comment by landreev** [comment]
Awesome, thank you Phil!

**Comment by scolapasta** [comment]
Closing this issue, as it's been installed.
