### ISSUE TITLE
Ongoing production DevOps tasks for the next sprint starting Feb. 15

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#246]
Per conversation with @cmbz, opening an issue for tracking normal/ongoing devops tasks that do not warrant dedicated issues, but still take some time.

**Comment by stevenwinship** [comment]
Google Sheets for tracking unscheduled DevOps tasks
https://docs.google.com/spreadsheets/d/1H_sjMYcAdeMMQNNpKHdHMHvi-6gow45ToCs_DEfhaTU/edit#gid=1386834576

**Comment by cmbz** [comment]
@stevenwinship or @scolapasta Please feel free to close this issue/move to Done and open up another one for the next sprint starting this afternoon. Thanks!
