### ISSUE TITLE
Dataset landing page: Thumbnails not displaying and text overlapping on view of dataset page

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse.harvard.edu#250]
dataset in question: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/EUP8EY

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/EUP8EY

<img width="972" alt="Screen Shot 2024-02-29 at 10 15 35 AM" src="https://github.com/IQSS/dataverse.harvard.edu/assets/8322346/d740e6ab-1a13-4ce3-a400-e1ddc942c173">

<img width="854" alt="Screen Shot 2024-02-29 at 10 15 40 AM" src="https://github.com/IQSS/dataverse.harvard.edu/assets/8322346/8f6aaafe-1e89-44f4-965f-04077e8314e0">

**Comment by qqmyers** [comment]
FWIW: Not sure why the images aren't there but the overflowing text is the alternative text for the image. It would probably be useful to add word-break:break-all to https://github.com/IQSS/dataverse/blob/b62c12369955ec2425d3ff23219e0cac75d5d189/src/main/webapp/resources/css/structure.css#L746 - that would limit it to showing in the square where the image should be. (So -this is not a fix but is perhaps something that could make the display look better if there are cases where the image is not available.)

**Comment by landreev** [comment]
TIFF again. For whatever reason the format is prone to failures when Dataverse tries to scale it. 

Don't know how to make the page handle it more gracefully (can try the css fix though). 
But the problem can likely be fixed by generating the thumbnails on the command line and pushing them into the s3 bucket.

**Comment by pdurbin** [comment]
We saw some similar overlap issues here:

- https://github.com/IQSS/dataverse/issues/7080

And there's a related issue:

- https://github.com/IQSS/dataverse/issues/10317

**Comment by landreev** [comment]
TIFF has been a problem forever. Always weirded me out, since it's one of the simplest formats ever - it's just an uncompressed bitmap table.

**Comment by landreev** [comment]
I generated and cached the thumbnails on the command line for the dataset. (The things I do out of :heart: for curation). 
Note that they are not particularly good-looking thumbnails - most of these TIFFs appear to be higher-rez, mostly black squares with just a few light dots here and there; like this one: https://dataverse.harvard.edu/api/access/datafile/8570264. So at 64 pixels many of them just become black squares, like the ones on page 1. The ones on page 7 are a little more interesting: 
![Screen Shot 2024-03-01 at 10 26 57 AM](https://github.com/IQSS/dataverse.harvard.edu/assets/737558/9177df34-0a75-4c21-a1d6-8fd7622153fe)
The ones still without thumbnails are obviously above the size limit. 
But at least the page isn't looking broken.

**Comment by sbarbosadataverse** [comment]
Created both tickets:

https://github.com/IQSS/dataverse/issues/10351
https://github.com/IQSS/dataverse/issues/10352

**Comment by landreev** [comment]
We likely already have opened issues that cover at least some of the above; that's why I wanted another developer to look into this before opening new ones. 
It's ok, we'll figure it out.

**Comment by cmbz** [comment]
2024/03/26
- Closing because dataset has been fixed. See also related: 
  - https://github.com/IQSS/dataverse/issues/10351
  - https://github.com/IQSS/dataverse/issues/10352
