### ISSUE TITLE
Ongoing production DevOps tasks for the next sprint starting March 14

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#252]

**Comment by landreev** [comment]
(will cc: everybody)

**Comment by landreev** [comment]
My understanding is that this "ongoing is devops stuff" is by design for tracking small stuff that would not warrant their own issues. 
The ongoing search engine performance issues in prod. is NOT such "small stuff" - it's a serious issue on its own.

**Comment by cmbz** [comment]
@landreev I agree.

**Comment by cmbz** [comment]
2024/03/27
- Closing for end of sprint. 
- @landreev will create a new one for the start of the next sprint
