### ISSUE TITLE
Ongoing production DevOps tasks for the next sprint starting March 27

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#257]

**Comment by landreev** [comment]
Found that the auto-cleanup script on demo wasn't working - had a hard-coded api token in it that had expired, doh. Fixed. 
Deleting the accumulated backlog now, will confirm here once done.

**Comment by landreev** [comment]
The accumulated backlog was mostly cleared yesterday. I extended the grace period a little bit, as a one off. But it will go back to the old strict rules starting with the next regularly scheduled cleaning. 

Speaking of the rules, the way it's defined in Kevin's script, it deletes datasets that haven't been *updated* in 30+ days (```and modificationtime < current_date-30```) as of the date the script is executed. So it's not going to touch an old dataset that somebody keeps playing with. 

This should be open to discussion if anyone believes the rules should be tightened, as to match the warning on the site. Alternatively, maybe the warning could be updated to reflect what's being enforced.

**Comment by cmbz** [comment]
Closing as complete! @landreev will open a new issue for Sprint 21 starting 10 April.
