### ISSUE TITLE
Reference website for Harvard Dataverse

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse.harvard.edu#26]
A website for information about Harvard Dataverse specifically. 

- [Site in progress](https://projects.iq.harvard.edu/aboutharvarddataverse)
- [Document for collaboration on content for launch](https://docs.google.com/document/d/1n8iToYT2ijranNOCYz4FzmFcA588n1-UtbqLG75eNzA/edit)
- [Wireframe document](https://docs.google.com/presentation/d/15sx4EzwmvTp8-JkPJsDL6wZjfuNfMJ-uYQOmwz8n2Vg/edit#slide=id.g5a55e24615_0_20).
- [Log of content from the perspective of creating curation outreach materials](https://docs.google.com/spreadsheets/d/1AOLB7Pi4jTCNeovgQAsaLSW95zULXmw55pqb4PdgGWI/edit#gid=0). 
- [Google DriveFolder of drafts of Sloan Educational Materials](https://drive.google.com/drive/u/1/folders/1SLoXTZzDBUtG548Nj4G1p11KMvlaeTDP)

**Comment by TaniaSchlatter** [comment]
Mercè would like this to be presented as a support site for Harvard Dataverse. This needs to be clear. Design should have a relationship to the Harvard Dataverse home page. Meeting scheduled with HUIT for template work:
Dataverse Website Chat – Organizer: Caro, Gabriel
Monday, October 7⋅3:00 – 4:00pm
1430 Mass Ave - 409 Conference Room

**Comment by TaniaSchlatter** [comment]
Checklist of work to be done: 
- [ ] Add new Support logo to the header – HUIT 
- [ ] Draft home page content – Mercè
- [ ] Get URL – request made to Open Scholar 11/13/19
- [ ] Dataverse Favicon – Dwayne
- Getting started for researchers page content:
    - [ ] Move content on dataverse.org 
    - [ ] Review and edit for only Harvard users
- Getting started for journals page content
    - [ ] Move content on dataverse.org
    - [ ] Review and edit for only Harvard users
- Getting started for groups page content
    - [ ] Move content on dataverse.org
    - [ ] Review and edit for only Harvard users
- Getting started page content. Once the content for the sections below has been reviewed:
    - [ ] summarize that content
    - [ ] provide an overview that applies for all users for this page
- Curation services page content:
    - [ ] Tania to follow up with Sonia and Ceilyn about status 
    - [ ] Rethink Dataverse.org home page content and re-draft
       - [ ]  delete/dramatically edit existing content on that page
- Policies and governance page content:
    - [ ] Tania to follow up with Sonia and Ceilyn – ok to do in phases
- [ ] Create link from Harvard Dataverse to the new support site

**Comment by jggautier** [comment]
Content from the "For Journal" and "For Institutions" pages are moved to the support website

**Comment by sbarbosadataverse** [comment]
Ceilyn and I will touch base this week.

**Comment by TaniaSchlatter** [comment]
Checklist for after launch:
- [ ] Rethink Dataverse.org home page content and re-draft
    - [ ] delete/dramatically edit existing content on that page
- Policies and governance page content:
    - [ ] Tania to follow up with Sonia and Ceilyn – ok to do in phases
- [ ] Create link from Harvard Dataverse to the new support site – Dataverse dev team

**Comment by TaniaSchlatter** [comment]
Checklist for HUIT for launch:
- [ ] url to support.dataverse.harvard.edu (requested)
- [ ] address logo position in the menu
- [ ] fix homepage so that all text shows
- [ ] link in the header to Harvard Dataverse to be in the same gold color used in the side nav. if possible

**Comment by TaniaSchlatter** [comment]
The checklist of IQSS work to be done before launch has been updated. Notes have been added to Ceilyn's feedback (https://docs.google.com/presentation/d/13nW10nnowvauLeci1ZCrHm3iJFLXbtVogtDMUIjIaLM/edit?usp=sharing)

**Comment by jggautier** [comment]
> Make navigation links work. Can we do this or is HUIT needed?

I changed the "Go to Harvard Dataverse >" link to point to the repository

- Changes made to [journals page](https://projects.iq.harvard.edu/aboutharvarddataverse/journals):
  - Made sure all of the text speaks to the user ("**your** journal can" instead of "**a** journal can")
  - Got rid of text about contacting us (since there are already "contact us" links on the page)
  - Got rid of some more redundant text
  - Fixed headings to match what's used on the "For Researcher" page. (The H tags cannot be trusted :( )

- Unresolved:
  - The title of the according, "How to set up your journal's dataverse" looks so big and out of place because it has an h3 class in the page's HTML (`<h3 class="ui-accordion-header"...>`) There's no way in the GUI to control what that text looks like.
    - We could edit the custom css to redefine the header tags, so that h3 is smaller (and we'd probably want to think about what sizes h2 and h1 should be and make sure they're used well and consistently across the site.)
    - Or we could ask the OpenScholar dev team to change `<h3 class="ui-accordion-header"...>` to another header (h4 is smaller but it's all caps; h5 is normal bold) or just don't use a header at all if possible. Not sure if this is part of the site theme.
    - Or we can not use an accordion, which I used (when I redid the page on dataverse.org) to try to make the page content easier to navigate...
  - Think of ways to make the page content easier to navigate. There's a main section and four sub-sections. Ceilyn suggested a nav bar on the left to jump to the four different sections on the page. It's possible for us to do this but not well. You'll see an example of that I mean on the left side. I also added anchor links in the first section to see if that'll help. Maybe the OpenScholar folks have solutions they've already used for other sites.

**Comment by TaniaSchlatter** [comment]
I asked the HUIT team if it is possible to change the H of the accordion style on the Journals page to an H5, along with a few other questions below. 

I edited all the bullets and numbered lists on the site to use Sentence case, and made a few formatting changes for consistency. 

> Hi Gabe, 
> 
> Thanks to you and Richard for helping us get this to the finish line. I have a few questions:
> Is it possible to change the color of the link in the header "Go to Harvard Dataverse"?
> On the Getting Started > Journals page, the accordion head is set to an H3, which is too large. We can not figure out how to change it. Can it be changed to an H5?
> On the same Journals page, the H3 heads on the page that the anchor links link to are blue. However, the heads themselves are not links, and should not be blue/indicated as clickable. They should be black as the other H3 heads. We have tried to change the color in the HTML, but it is not changing. Can they be changed?
> - Tania

**Comment by jggautier** [comment]
On the Journals page, yesterday HUIT improved the header style of the accordion and changed the style of the anchor links.

They also added the orange/gold color to the "Go to Harvard Dataverse" link on the nav bar.

**Comment by djbrooke** [comment]
A few updates:

- support.dataverse.harvard.edu is now live (the box is checked above, adding another checkbox to verify links. Most work.)
- OS is doing a search redesign as part of their Drupal 8 efforts.
- There's a typo in the footer (datavese) but I don't have admin access (checkbox added above)
- We may need to include an accessibility statement on support.dataverse.harvard.edu (checkbox added above, based on discussion with @mheppler and @TaniaSchlatter in #46

**Comment by jggautier** [comment]
> There's a typo in the footer (datavese) but I don't have admin access (checkbox added above)

Typo fixed (and checkbox checked). Also gave you admin access to the site :)

**Comment by pdurbin** [comment]
The new site looks great but I couldn't easy find information on upload (2.5 GB per file?) or storage limits (1 TB?). Here is how these questions are sometimes phrased:

- "Is there a space limit on what any given institution or user can place in the Dataverse? How much can we put in there?!" -- https://groups.google.com/d/msg/dataverse-community/HqnMk1RzNzo/c_mHQv0eAAAJ
- "If yes, is there any size limitation on harwerd and how long Harward will support this. I may expect to have assay 100 TB data in next 2 years?" -- https://groups.google.com/d/msg/dataverse-community/zn8fik2GgXI/I3GalBJXBwAJ

Apologies if this information is already on the new site and I simply couldn't find it!

**Comment by TaniaSchlatter** [comment]
@pdurbin I added upload file size information, as well as a written explanation of what Harvard Dataverse is (the video explains it well), who can deposit and access, and that use is free.

**Comment by mheppler** [comment]
First accessibility reports from SiteImprove are in...

![Screen Shot 2020-01-08 at 11 38 40 AM](https://user-images.githubusercontent.com/687227/71997575-1a45cd80-320c-11ea-829b-3a648b4bf2b9.png)

**Comment by pdurbin** [comment]
During design standup this morning I mentioned that it shouldn't be hard to change the "About" link for Harvard Dataverse to the new support/reference website. Here's the "small chunk" issue I just created:

- Change Harvard Dataverse "About" link to support.dataverse.harvard.edu (new support site) #60

**Comment by TaniaSchlatter** [comment]
Tracking suggestions and planned improvements post-launch here: #67
