### ISSUE TITLE
Ongoing production DevOps tasks for the next sprint starting April 10

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse.harvard.edu#264]

**Comment by landreev** [comment]
Some ongoing tasks: 
Demo has been upgraded to 6.2. 
Need to schedule a date for the prod. upgrade as well. Will track it here for now; will open a separate issue if it turns out to be a project. It has been confirmed that we will have to build and deploy a custom patch - not a stock 6.2 - at the very least it will need to have the Globus fixes from IQSS/dataverse#10450 added.

**Comment by landreev** [comment]
Meeting with Joe Weiner from HUIT in 3 minutes about tightening security for dataverse.org that may require an update of its DNS record.

**Comment by landreev** [comment]
For the record, dataverse.org transition was super smooth, they were able to do everything without needing anything from us/me. There was only about a 10 min.  window where the cert on the load balancer was complaining about the name, before it was updated. 
Unfortunately, we appear to have lost www.dataverse.org that OpenScholar no longer recognizes. It's a cname alias of dataverse.org; I wasn't consciously aware of its existence - but apparently we have it listed in a couple of places. 

Trying to reach Joe/HUIT to get it fixed.

**Comment by landreev** [comment]
(the above is HUIT ticket INC05414705)

**Comment by landreev** [comment]
www.dataverse.org still dead. Hmm. A bit hard to see why this would be non-trivial at all. (They have already fixed the ssl cert to recognize the name; it's the final redirect to dataverse.org that's not working). 

I should be able to fix it myself fairly quickly - by changing the cname to point to demo.dataverse.org (which already uses a star cert for *.dataverse.org) and set up a vhost there redirecting to dataverse.org; should work, right? - I'll offer to do this to Joe if it doesn't come back to life on their end soon.

**Comment by landreev** [comment]
I will go ahead and create a dedicated issue for the prod. 6.2 upgrade; with custom patch in the picture, it's a bit less trivial than a regular, run-of-the-mill upgrade.

**Comment by landreev** [comment]
OK, done. 
"not pretty,  but  works" being the key words

> Some ongoing tasks: Demo has been upgraded to 6.2. Need to schedule a date for the prod. upgrade as well. Will track it here for now; will open a separate issue if it turns out to be a project. It has been confirmed that we will have to build and deploy a custom patch - not a stock 6.2 - at the very least it will need to have the Globus fixes from [IQSS/dataverse#10450](https://github.com/IQSS/dataverse/issues/10450) added.

**Comment by landreev** [comment]
This was done, as of yesterday. "not pretty, but works".

> [www.dataverse.org](http://www.dataverse.org) still dead. Hmm. A bit hard to see why this would be non-trivial at all. (They have already fixed the ssl cert to recognize the name; it's the final redirect to dataverse.org that's not working).
> 
> I should be able to fix it myself fairly quickly - by changing the cname to point to demo.dataverse.org (which already uses a star cert for *.dataverse.org) and set up a vhost there redirecting to dataverse.org; should work, right? - I'll offer to do this to Joe if it doesn't come back to life on their end soon.
