### ISSUE TITLE
Searchable Facets: Searchable facets displayed for CAFE collection should reflect the metadata in the searchable facets dialogue box EDIT-General Information

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse.harvard.edu#265]
The CAFE collection displays a long list of searchable facets on the collection landing page but when you navigate to the EDIT - GENERAL INFORMATION, FACETS dialogue box, it's empty.

![Screen Shot 2024-04-16 at 12 55 16 PM](https://github.com/IQSS/dataverse/assets/8322346/43286b1d-1a8e-4633-a657-cc82f6ad6c39)

![Screen Shot 2024-04-16 at 12 55 05 PM](https://github.com/IQSS/dataverse/assets/8322346/f00fc18f-0fcd-4923-9b68-ae85f95f04d1)

**Comment by scolapasta** [comment]
@sbarbosadataverse I'm going to go ahead and close this, unless you've seen it happen again. Regardless, the SPA is coming, and the issue won't happen there.
