### ISSUE TITLE
Create "Saved Search" so that Dean Karlan-authored datasets are linked into the DFEEP collection

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#277]
A depositor, Dean Karlan, would like all datasets he's an author on to be added as links into the [Datahub for Field Experiments in Economics and Public Policy (DFEEP) collection](https://dataverse.harvard.edu/dataverse/DFEEP).

Searching by author name, [https://dataverse.harvard.edu/dataverse/harvard?q=authorName:"Karlan,+Dean"&types=datasets](https://dataverse.harvard.edu/dataverse/harvard?q=authorName:%22Karlan,+Dean%22&types=datasets) returns 54 datasets he's an author on as of this writing. All but 12 of those datasets are already in the DFEEP collection.

I was able to add to the DFEEP collection links to 11 of those 12 datasets. The dataset I couldn't add a link for is at https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/QT7IXR, which is one of the three datasets I listed in [the GitHub issue I opened about not being able to add links for certain datasets into Dean Karlan's collection](https://github.com/IQSS/dataverse.harvard.edu/issues/274).

To continue creating links of Dean Karlan-authored datasets that will be published later, I think we should create a ["Saved Search"](https://guides.dataverse.org/en/6.2/api/native-api.html#saved-search).

For more context, see the email conversation at https://help.hmdc.harvard.edu/Ticket/Display.html?id=359122.

This is related to another GitHub issue at https://github.com/IQSS/dataverse.harvard.edu/issues/275 about using the "Saved Search" feature so that Dean Karlan-authored datasets published outside of his collection are linked into his collection.

**Comment by jggautier** [comment]
I just learned that superusers can create "Saved Searches". I did this to link Dean Karlan-authored datasets into the DFEEP collection and I'll confirm that the links were created.

**Comment by sbarbosadataverse** [comment]
Saved Search may not be an immediate "change" because of indexing. Julian will check the search he created tomorrow and see if all was successful. In any case, this needs to be documented in the Guide or fixed, or added to the success message that there is a delay between the action and the results. Success message may say "this action takes 24 hours" ?

**Comment by jggautier** [comment]
The 12 dataset links that I couldn't add in Dean Karlan's collection have not been added.

**Comment by jggautier** [comment]
@sbarbosadataverse , I created a GitHub issue at https://github.com/IQSS/dataverse/issues/10628 about improving the Saved Search feature and added a link to your comment in this issue.
