### ISSUE TITLE
Upgrade HDV prod. to 6.3 

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#285]
Don't want to jinx it, but we may for once be able to deploy a stock .war file, without having to build a patched version.

**Comment by pdurbin** [comment]
In the context of this issue...

- https://github.com/IQSS/dataverse-pm/issues/163

... we are hoping the "License" facet is fully populated so that we can use it to find CC0 datasets.

It looks like reindexing is already part of the 6.3 release notes (as part of upgrading Solr).

**Comment by landreev** [comment]
Prod. has been upgraded. I'll need a bit more time to populate the license facet. I'm realizing that there may still be more "Custom Terms" entries in that facet than we would prefer. There will be significantly fewer, because of the fixes in IQSS/dataverse#10614 (harvested datasets w/out any license/terms of use are not going to be indexed as "Custom Terms", for one). But, a fairly large number of older local datasets will still have custom terms instead of CC0 1.0, until IQSS/dataverse#10634 is applied, I think - need to confirm/see if I should run that sooner.

**Comment by cmbz** [comment]
Thanks @landreev!
