### ISSUE TITLE
Set up a Shibboleth Group for Tufts University

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#29]
We should set up a Shibboleth Group for Tufts following the instructions here:

http://guides.dataverse.org/en/latest/installation/shibboleth.html#institution-wide-shibboleth-groups

I'm happy to learn and work with someone on this if I can have the appropriate access to make the changes.

**Comment by kcondon** [comment]
OK, should be all set:

curl http://localhost:8080/api/admin/groups/shib

{"name":"All Tufts University Shibboleth Users","attribute":"Shib-Identity-Provider","pattern":"https://shib-idp.tufts.edu/idp/shibboleth","id":4}

**Comment by djbrooke** [comment]
Moving to Done. Thanks @kcondon !
