### ISSUE TITLE
Add Croissant exporter to Harvard Dataverse (and demo)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse.harvard.edu#294]
This is a subtask for our collaboration with Kaggle:

- https://github.com/IQSS/dataverse-pm/issues/163

Once the following pull request has been merged...

- https://github.com/IQSS/dataverse/pull/10533

... we can consider the Croissant exporter good enough for production use and add it to Harvard Dataverse.

As of this writing the latest version is 0.1.2: https://repo1.maven.org/maven2/io/gdcc/export/croissant/

I'm not sure if Harvard Dataverse already has [dataverse.spi.exporters.directory](https://guides.dataverse.org/en/6.3/installation/config.html#id348) configured or not, but it will be needed for the jar file to be detected.

Note that this will change what appears in the `<head>` of dataset pages as explained here:

- https://dataverse-guide--10533.org.readthedocs.build/en/10533/admin/discoverability.html#schema-org-head
- https://github.com/IQSS/dataverse/pull/10382

There is no need to wait until the [upgrade to 6.3](https://github.com/IQSS/dataverse.harvard.edu/issues/285) (but it wouldn't hurt).

It would be nice to add the Croissant exporter to [demo](https://demo.dataverse.org) as well, because I've communicated to @goeffthomas from Kaggle that demo can be used for testing. (I already put the exporter on [beta](https://beta.dataverse.org).)

**Comment by stevenwinship** [comment]
Croissant exporter added to both Harvard Dataverse and Demo
