### ISSUE TITLE
Implement support for Local Context controlled vocabulary support on demo.dataverse.org

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse.harvard.edu#297]
## Overview
- Dataverse installations now have the option to support the [Local Context](https://localcontexts.org/) [Traditional Knowledge Labels](https://localcontexts.org/labels/traditional-knowledge-labels/) as a controlled vocabulary feature. 
- For details, see: https://github.com/gdcc/dataverse-external-vocab-support/pull/23

We need to **test the feature on demo.dataverse.org** to make progress towards the following NIH GREI task: 
- https://github.com/IQSS/dataverse-pm/issues/170

## Related 
- https://github.com/gdcc/dataverse-external-vocab-support/pull/22
- https://github.com/IQSS/dataverse/pull/10712

**Comment by cmbz** [comment]
2024/07/27
- Sized at 3 based on @qqmyers recommendation. Increase size if needed to address other factors such as UI or more in-depth functionality testing.

**Comment by stevenwinship** [comment]
Implemented on demo.dataverse.org

![image](https://github.com/user-attachments/assets/64527bf5-808e-47ba-8d86-8291c4cf226b)
