### ISSUE TITLE
Install Voyager, the Smithsonian 3D Viewer on demo.dataverse.org for user testing

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse.harvard.edu#299]
## Overview
- @qqmyers Performed work to implement the Smithsonian 3D previewer called [Voyager](https://smithsonian.github.io/dpo-voyager/) as a Dataverse previewer
- This is a beta test of Voyager as a Dataverse previewer. 
- Related issues below have been merged, including support for required 3D MIME type
- Next steps: 
  - Install the previewer on demo.dataverse.org 
  - Make available for testing by users with 3D data, including @sbarbosadataverse and @Cook4986

## Sample Datasets
- [Cluny Capital](https://dataverse.harvard.edu/file.xhtml?fileId=6931827&version=1.0)
- [Medical Training Head](https://dataverse.harvard.edu/file.xhtml?fileId=6193074&version=2.0)
- [DeelFontein Meteorite](https://dataverse.harvard.edu/file.xhtml?fileId=6813019&version=1.0)
- [Camera Obscura](https://dataverse.harvard.edu/file.xhtml?fileId=5014788&version=1.0)

## Installation Instructions
Installing the previewer follows the standard pattern:
 - Run the curl command at https://github.com/gdcc/dataverse-previewers/blob/develop/6.1curlcommands.md#smithsonian-voyager-3d-model-previewer-beta

To enable Dataverse to recognize the MIME type for *.glb files, you can either:
- Cherry pick all of #10760
- Edit the local MimeType* files (in the exploded war's WEB-INF/classes/propertyFiles dir to add the same 3 lines as in #10760 and restart the server

Note #10760 has been merged, so it should be on the beta server. The Dataverse update step wouldn't be needed there. 

## Related
- https://github.com/gdcc/dataverse-previewers/issues/57
- https://github.com/Smithsonian/dpo-voyager/issues/297 (please note fixes made by Smithsonian team)
- https://github.com/IQSS/dataverse/pull/10760
- https://github.com/gdcc/dataverse-previewers/pull/77

**Comment by stevenwinship** [comment]
Voyager viewer is now available on beta.dataverse.org and demo.dataverse.org

The Open in New Window is failing:

![image](https://github.com/user-attachments/assets/3eb72673-34f7-4f66-87e7-61e931603015)

**Comment by qqmyers** [comment]
Good catch! The example curl command at https://github.com/gdcc/dataverse-previewers/blob/develop/6.1curlcommands.md#smithsonian-voyager-3d-model-previewer-beta was incorrect - fixed now. You'll need to delete the external tool you added via that command and rerun the curl command to fix things. (Or could edit the db). Should be able to GET http://localhost:8080/api/admin/externalTools to see the installed tools and get the ID of the existing voyager entry and then DELETE http://localhost:8080/api/admin/externalTools/{id} . (From memory - if there are problems those calls should be in the giude.)

**Comment by stevenwinship** [comment]
I updated both beta and demo databases with the new external tool config. They both work now when clicking on "Open in New Window"

**Comment by cmbz** [comment]
2024/08/14
- Closing now, testing will continue and we'll open new issues if needed.
