### ISSUE TITLE
Ongoing prod. DevOps 08-15 - 08-28

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#301]

**Comment by landreev** [comment]
Star certificate for `*.dataverse.org`,  that's used on demo, beta, guides etc. servers has expired and would not auto-renew, requiring domain ownership validation. Feels like a time-consuming affair.

**Comment by tuanpham96** [comment]
Does this affect the API? One of the examples from the the search API guide doesn't return anything. Let me know if this should be posted elsewhere.

On browser: `https://demo.dataverse.org/api/search?q=trees` this returns

```json
{
  "status": "OK",
  "data": {
    "q": "trees",
    "total_count": 0,
    "start": 0,
    "spelling_alternatives": {},
    "items": [],
    "count_in_response": 0
  }
}
```

Can't seem to use `curl` here either

```shell
$ curl http://demo.dataverse.org/api/search?q=trees

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://demo.dataverse.org/api/search?q=trees">here</a>.</p>
</body></html>

$ curl https://demo.dataverse.org/api/search?q=trees

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by qqmyers** [comment]
The cert for demo.dataverse.org expired and it's getting replaced. Until then adding -k to the curl command will get you past the error. API calls would similarly have to ignore the bad cert temporarily to work with demo.

**Comment by landreev** [comment]
@tuanpham96 
demo.dataverse.org should be back in business. 
As for the actual search, `https://demo.dataverse.org/api/search?q=trees` - zero results is correct, there are no datasets with "trees" there at the moment. But if you search for some common word, you should get results: 
```
curl "https://demo.dataverse.org/api/search?q=test"
{
  "data": {
    "count_in_response": 10,

... edited for brevity...
    "total_count": 704,
    "q": "test"
  },
  "status": "OK"
}
```

**Comment by tuanpham96** [comment]
awesome! thanks for the quick update!
