### ISSUE TITLE
Deploy updated TK Labels metadata block to demo

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse.harvard.edu#303]
## Overview
- Dataverse installations have the option to support the [Local Context](https://localcontexts.org/) [Traditional Knowledge Labels](https://localcontexts.org/labels/traditional-knowledge-labels/) as a controlled vocabulary feature.
- Support was added to demo.dataverse.org to test this feature. See https://github.com/IQSS/dataverse.harvard.edu/issues/297
- The functionality is currently undergoing revisions. See: https://github.com/gdcc/dataverse-external-vocab-support/issues/24
- Once revisions are complete, the revised block needs to be added to demo.dataverse.org again for testing
- This issue documents the need to upload the revision on demo.dataverse.org

## Details
- Please see this comment: https://github.com/IQSS/dataverse.harvard.edu/issues/303#issuecomment-2319130653

## Depends On
- https://github.com/gdcc/dataverse-external-vocab-support/issues/24

## Related
- https://github.com/IQSS/dataverse-pm/issues/170
- https://github.com/IQSS/dataverse.harvard.edu/issues/297
- https://github.com/gdcc/dataverse-external-vocab-support/pull/23

**Comment by cmbz** [comment]
@stevenwinship @sbarbosadataverse Just putting this issue on your radar for an upcoming sprint (soon). Once @qqmyers has completed this issue https://github.com/gdcc/dataverse-external-vocab-support/issues/24 we'll be ready to go.

**Comment by qqmyers** [comment]
FWIW: There won't be any change to the block itself (so also no change in solr), but the registration of the external vocabulary script will need to be redone.

**Comment by qqmyers** [comment]
Demo has been updated. Details in https://github.com/IQSS/dataverse-pm/issues/170#issuecomment-2327036420.

**Comment by cmbz** [comment]
Thanks @qqmyers can I simply close this one?

**Comment by cmbz** [comment]
Closing as completed, per https://github.com/IQSS/dataverse-pm/issues/170#issuecomment-2327036420
