### ISSUE TITLE
Test the NESE-disk Globus configuration in production 

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#305]
Unlike the NESE-tape setup, where we have one prod. user (OMAMA), the similar NESE-disk storage allocation they created for us has not been tested just yet. Since we have one potential depositor for this service as well, we need to verify that it's actually working. 
There is every reason to expect that it will just work (at least as well as the tape version that is), since the 2 setups are largely identical. Everything that needed to be done on the NESE side _should_ be done (storage allocated, Globus roles and permissions etc. created). But, it's just something we haven't done yet, so needs to be confirmed for the fact before we let any users start uploading stuff. 

Both upload and download need to be tested.

Also, it would definitely help to deploy 6.4 first, since it contains the improvements made specifically to make long-running Globus uploads more reliable. But that is ready to go as well.  

## Related
- https://github.com/IQSS/dataverse-HDV-Curation/issues/582

**Comment by landreev** [comment]
For posterity, prod. configuration: 

```
/opt/dvn/app/payara6/bin/asadmin create-jvm-options "\-Ddataverse.files.globusND.type=globus"
/opt/dvn/app/payara6/bin/asadmin create-jvm-options "\-Ddataverse.files.globusND.label=NESEdisk"
/opt/dvn/app/payara6/bin/asadmin create-jvm-options "\-Ddataverse.files.globusND.managed=true"
/opt/dvn/app/payara6/bin/asadmin create-jvm-options "\-Ddataverse.files.globusND.base-store=s3"
/opt/dvn/app/payara6/bin/asadmin create-jvm-options "\-Ddataverse.files.globusND.remote-store-name=NESEdisk"
/opt/dvn/app/payara6/bin/asadmin create-jvm-options "\-Ddataverse.files.globusND.globus-token=[redacted (same application role/auth token as with NESE Tape)]"
/opt/dvn/app/payara6/bin/asadmin create-jvm-options "\-Ddataverse.files.globusND.upload-out-of-band=true"
/opt/dvn/app/payara6/bin/asadmin create-jvm-options "\-Ddataverse.files.globusND.transfer-endpoint-with-basepath=[redacted]"
/opt/dvn/app/payara6/bin/asadmin create-jvm-options "\-Ddataverse.files.globusND.files-not-accessible-by-dataverse=true"
/opt/dvn/app/payara6/bin/asadmin create-jvm-options "\-Ddataverse.files.globusND.dataverse-inaccessible=true"
```

**Comment by landreev** [comment]
@cmbz It all worked as expected, the configuration was added (again, it's largely identical to the existing NESE tape setup, just needed both servers restarted to activate). Everything appears to be working as expected on the NESE side as well. So, I'm planning to close the issue without further ado.

**Comment by cmbz** [comment]
@landreev That's great news! Congrats and thank you! :)
