### ISSUE TITLE
remove Whole Tale (temporarily down) from demo

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse.harvard.edu#308]
Back in 2019 we added Whole Tale to https://demo.dataverse.org in this issue...

- https://github.com/IQSS/dataverse/issues/6446

... however, Whole Tale is transitioning to a new host, which may take several weeks.

I'd like to suggest we remove the Whole Tale button from demo for now.

Once Whole Tale is back up, perhaps we can use the following issue to add it back to demo and add it to Harvard Dataverse:

- https://github.com/IQSS/dataverse.harvard.edu/issues/209

**Comment by cmbz** [comment]
2024/10/16: @pdurbin I've added the issue to _This Sprint_ to raise at standup today.

**Comment by pdurbin** [comment]
It was 10 id. I removed it:

```
[rocky@ip-172-31-6-84 ~]$ curl http://localhost:8080/api/admin/externalTools/10
{"status":"OK","data":{"id":10,"displayName":"Whole Tale","description":"Analyze in Whole Tale","types":["explore"],"scope":"dataset","toolUrl":"https://data.wholetale.org/api/v1/integration/dataverse","toolParameters":"{\"queryParameters\":[{\"datasetPid\":\"{datasetPid}\"},{\"siteUrl\":\"{siteUrl}\"},{\"key\":\"{apiToken}\"}]}"}}[rocky@ip-172-31-6-84 ~]$ 
[rocky@ip-172-31-6-84 ~]$ curl -X DELETE http://localhost:8080/api/admin/externalTools/10
{"status":"OK","data":{"message":"Deleted external tool with id of 10"}}
```
