### ISSUE TITLE
Feedback form for usability recruiting directs questions to invalid email address

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse.harvard.edu#31]
![Screen Shot 2019-09-24 at 11 50 42 AM](https://user-images.githubusercontent.com/21006/65528185-e98e9200-dec1-11e9-9e6c-67f2d1cbb18a.png)
![Screen Shot 2019-09-24 at 11 52 05 AM](https://user-images.githubusercontent.com/21006/65528186-e98e9200-dec1-11e9-932d-ddf3e7eed87c.png)

**Comment by jggautier** [comment]
For now I changed the name and contact info to @TaniaSchlatter's. Is that okay, Tania? The form is at https://docs.google.com/forms/d/10RbKx3vA1nQRRpOTYS8yQjtrfmWKkTP0xtKlO903-Oc.

**Comment by jggautier** [comment]
Closing :)

**Comment by pdurbin** [comment]
While reviewing https://github.com/IQSS/dataverse/pull/6223 I noticed CONTRIBUTING.md says, "Please email us at support@dataverse.org if you are interested in participating in usability testing."

This is unchanged from what appears at https://github.com/IQSS/dataverse/blob/v4.16/CONTRIBUTING.md#usability-testing
