### ISSUE TITLE
add CSV (and TSV) Previewer external tool

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse.harvard.edu#38]
It's amazing! I just tried it out at https://dev2.dataverse.org and here are some screenshots:

![Screen Shot 2019-10-04 at 6 03 56 PM](https://user-images.githubusercontent.com/21006/66243414-917e3980-e6d2-11e9-8e08-94ce57aad183.png)
![Screen Shot 2019-10-04 at 6 04 05 PM](https://user-images.githubusercontent.com/21006/66243415-917e3980-e6d2-11e9-91ea-e381aa63ffa8.png)

We'll be adding this to new external tool to the guides as part of https://github.com/IQSS/dataverse/issues/6256

**Comment by 4tikhonov** [comment]
Everything as [promised](https://www.slideshare.net/vty/dataverse-in-the-european-open-science-cloud/9) during last Community meeting. :)
We're moving fast now, I'm sharing only production ready stuff.

**Comment by jggautier** [comment]
It's possible to view tabular data that's been uploaded and ingested by Harvard Dataverse Repository (e.g. https://dataverse.harvard.edu/file.xhtml?fileId=6768467&version=1.0) and Demo Dataverse (https://demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/RLSTIA/3ZA0ZP). I think it's using the external tool @pdurbin mentioned.

Closing this issue. Feel free to re-open if there's an aspect to this that hasn't been done.

**Comment by pdurbin** [comment]
Yep! All set! Looks great! Thanks!
