### ISSUE TITLE
Add previewers to dataverse.harvard.edu

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#42]
Once we finish #3758 and #6210, we should add these previewers to production.

**Comment by kcondon** [comment]
@djbrooke OK, all previewers added, take a look.

**Comment by djbrooke** [comment]
Thanks Kevin, I'm seeing that as well. Let's discuss to see if it's something small we're missing, and if not we can take down the previewers for now and re-approach after some investigation.

**Comment by djbrooke** [comment]
To summarize:

- This .tab file previews successfully: https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/UEOK3H/RAVQSR
- This .pdf file does not preview successfully: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/QUH8KT. It just spins and shows nothing in both in the preview window and in the external tool view.
- This .txt file does not preview successfully: https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/GKJWUG/4WWEOC. It shows the error "Unable to retrieve file. If problem persists (has your login timed out?), report error code: error to the repository administrator."

**Comment by djbrooke** [comment]
Adding @scolapasta here to lead the discussion in tech hours about how to get these previewers active on prod. We will not make any changes to the configuration this week, but it will be good to get a plan in place to execute on soon in the new year.

**Comment by djbrooke** [comment]
@kcondon, thanks for your previous troubleshooting on this. LTS has enabled CORS on dataverse.harvard.edu so these should work now. Can you please try to enable this again? Thank you!

**Comment by kcondon** [comment]
@djbrooke Done and example issues are resolved.
