### ISSUE TITLE
Upgrade Shibboleth on Harvard Dataverse

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#5]
In https://github.com/IQSS/dataverse/issues/5387 we upgraded shibboleth for the Dataverse software. We should follow on by actually upgrading production once 4.12 is out.

**Comment by djbrooke** [comment]
This is a document verification, we've updated dataverse.harvard.edu and it's worked.

**Comment by landreev** [comment]
This has been done; the new shib has been working in prod. for a while now. 
The schema version in the config file is irrelevant (hasn't changed between the releases). 
The mysterious shibd deaths in prod. are being successfully handled by a restart cronjob.
