### ISSUE TITLE
OAI-ORE exports of some datasets are different than others

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#50]
The OAI-ORE export of [this dataset](https://doi.org/10.7910/DVN/ZSAIM3) in Harvard Dataverse is different than other datasets' OAI-ORE exports (and different than what's expected).

Specifically, the `ore:describes` and `@context` sections of [the OAI-ORE export of Dataset 1](https://dataverse.harvard.edu/api/datasets/export?exporter=OAI_ORE&persistentId=doi%3A10.7910/DVN/ZSAIM3) are different than [the OAI-ORE export of Dataset 2](https://dataverse.harvard.edu/api/datasets/export?exporter=OAI_ORE&persistentId=doi%3A10.7910/DVN/J6UKTC):

<img width="1292" alt="oai_ore" src="https://user-images.githubusercontent.com/18374574/71382550-7d95f580-25a6-11ea-9b61-f70cbb97c6f1.png">

So in the `ore:describes` section of Dataset 1, the author key is "citation:Author", and in Dataset 2, the author key is "Author." Some other keys in the Dataset 1 export start with "citation:", where they don't in the Dataset 2 export.

Is this because the mapping being done in the `@context` sections are different? In the `@context` section of Dataset 2, there's an Author field mapped to dcterms:creator, and other fields mapped to dcterms. For Dataset 1, none of the listed fields in the `@context` section are mapped to dcterms.

Will re-exporting the OAI-ORE metadata of the first dataset correct this issue? (I think there's an admin-only API endpoint to re-export a dataset's metadata, but I couldn't find it in the guides.)

I downloaded and checked the OAI-ORE exports of a few other datasets but couldn't find any others like Dataset 1. Is there a way to see if any other datasets have OAI-ORE metadata like Dataset 1? (Besides downloading every dataset's OAI-ORE export and writing scripts to search through them all?)

There are some other weird things about the metadata in Dataset 2 (like its `@context` section listing Author/Citation and author/citation fields and mapping them to different things), but I figured that could be explored once all of the OAI-ORE exports were following the same rules.

**Comment by pdurbin** [comment]
> I think there's an admin-only API endpoint to re-export a dataset's metadata

From a quick look I couldn't find an API endpoint to re-export a single dataset's metadata. You might be remembering "reExportAll" at http://guides.dataverse.org/en/4.18.1/admin/metadataexport.html

For a single dataset we could delete the export from disk (S3 in the case of Harvard Dataverse) and then export it again so that we get a fresh copy and can see if the format changes. I'm not aware of any changes that we made but it sure sounds backward-incompatible to me.

**Comment by jggautier** [comment]
The issue is with the OAI-ORE exports of multiple datasets. I checked about 1500, and 66 have exports similar to dataset 1 in the screenshot above. The parsed metadata is in this attached csv file: [oai-ore.txt](https://github.com/IQSS/dataverse.harvard.edu/files/4106499/oai-ore.txt)

It seems like the update to 4.19 will include a reExportAll, so I plan to check the OAI-ORE exports when Harvard Dataverse updates to 4.19.

Also, the propositions in https://github.com/IQSS/dataverse/issues/6497 give me the impression that this issue will be sorted out as work continues on the OAI-ORE exports.

**Comment by jggautier** [comment]
I re-checked OAI-ORE exports of a few hundred datasets and this inconsistency seems to have been fixed when the reExportAll endpoint was run on Harvard Dataverse recently (as part of the upgrade to 4.19). I'm closing this issue since how Dataverse fields are mapped to URIs will be discussed in other efforts (e.g. https://github.com/IQSS/dataverse/issues/6497).

Also, this inconsistency may have not been fixed for all datasets in Harvard Dataverse due to issues with the API endpoint, but those issues are described and being tracked in https://github.com/IQSS/dataverse/issues/6594.
