### ISSUE TITLE
Add full text indexing to Harvard Dataverse

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#51]
Dataverse can index the content of text files, so that people's searches include the text in text files, like pdfs and .txt files (https://github.com/IQSS/dataverse/issues/5030). This issue is for discussion of enabling full text indexing on the Harvard Dataverse repository.

It's been enabled on QDR's repository (QDR developed the feature).

**Comment by pdurbin** [comment]
I believe this is a duplicate of #47 but the description is better, I think.

**Comment by jggautier** [comment]
Thanks! @sbarbosadataverse told me she opened an issue, too, but I couldn't find it. Closing this one.
