### ISSUE TITLE
Consider testing and adding file previewer for .wave audio files (using QDR's dataverse previewers)

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse.harvard.edu#54]
A Harvard Dataverse user saw that other file types were previewable and asked if .wave files could be, too.

The curl commands listed in the GitHub repo for QDR's dataverse file previewers don't include a command for adding a .wave audio file previewer.  @qqmyers provided helpful tips in this GitHub issue I opened in the file previewer's GitHub repo: https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers/issues/36

.wave files seem to play well in the latest versions of Chrome, Firefox and Safari for MacOS. They play well in the Edge browser, but not in the more recent version of IE. (According to https://hpr.dogphilosophy.net/test/, no audio file types play in IE...)

**Comment by jggautier** [comment]
There's discussion in [this Google Groups thread](https://groups.google.com/d/msg/dataverse-community/L4-CHOkAnuM/_BO3Vd04AgAJ) about how .wave files can be assigned different mimetypes, so other mimetypes should be included to ensure that Dataverse is able to preview as many .wave files as possible.

**Comment by qqmyers** [comment]
FWIW: the issue mentioned in the first comment above moved to the GDCC repo along with the code: https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers/issues/36

**Comment by jggautier** [comment]
Thanks! I just updated the link in the original comment.

**Comment by jggautier** [comment]
Just mentioning here that there's more discussion to keep an eye on in the recent Google Group thread at https://groups.google.com/g/dataverse-community/c/CE0T1x8Lg5s/m/_2Ft4Jm4AQAJ about previewing .wav files.

**Comment by jggautier** [comment]
Looks like a file previewer for .wave audio files was added to Harvard Dataverse, though I'm not sure when or who added it.

Using the latest versions of Chrome, Firefox and Safari, I was able to play the .wave files in the dataset at https://doi.org/10.7910/DVN/XA6YXG.

The larger wave files in the dataset at https://doi.org/10.7910/DVN/GDWOWZ wouldn't play.

I'm closing this GitHub issue.
