### ISSUE TITLE
Preview is not working

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse.harvard.edu#59]
The preview function is not working due to the changing URL of the external service.

See for example: https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/9ERCTY/CEDY3H

To solve the problem, you can do the following steps:

a. Get the list of IDs of external tools

```
curl http://localhost:8080/api/admin/externalTools | jq '.data[].id'
```

It gives all the IDs of the external tools.

b. Delete external tools individually:

```
curl -X DELETE http://localhost:8080/api/admin/externalTools/1
curl -X DELETE http://localhost:8080/api/admin/externalTools/2
curl -X DELETE http://localhost:8080/api/admin/externalTools/3
curl -X DELETE http://localhost:8080/api/admin/externalTools/4
curl -X DELETE http://localhost:8080/api/admin/externalTools/5
curl -X DELETE http://localhost:8080/api/admin/externalTools/6
...
```

(Please use the IDs extracted in the previous step.)

c. copy the curl command from the README of the external preview tool (https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers/blob/master/README.md)

d. replace https://qualitativedatarepository.github.io to https://globaldataversecommunityconsortium.github.io

e. run the modified curl commands

**Comment by pdurbin** [comment]
@pkiraly thanks for creating this issue!

Team, please see these related issues:

- https://github.com/IQSS/dataverse/issues/6616
- https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers/issues/38

**Comment by djbrooke** [comment]
@pkiraly thanks for reporting and @pdurbin for bumping. Since the previewers are back at QDR and working again I'm going to close this for now but I'll revisit with @qqmyers the longer terms plans for this and when we should make the switch. Thanks again!
