### ISSUE TITLE
Fix issue with problematic dataset

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#6]
This dataset is causing issues when we try to publish it in production:

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/7NRLEG

The ampersand in the title may be part of the issue.

**Comment by pdurbin** [comment]
It's possible that https://github.com/IQSS/dataverse/issues/3328 is related. We recently moved from EZID to DataCite, which is more strict.

**Comment by djbrooke** [comment]
@landreev - I'm going to close this as the dataset publish was handled as a one off in prod and #5598 is the code fix that will reduce the chances of this happening in the first place.  I asked the folks from MIT Libraries to not make changes and check with us if they need to republish before we put the fix in place. 

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZCPMU6
