### ISSUE TITLE
Harvest CGIAR installations

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse.harvard.edu#61]
Leroy from CGIAR asked us to consider Harvesting the following, as we already Harvest some of the other Centers and Programs

ICARDA - https://data.mel.cgiar.org/
CIP - https://data.cipotato.org/dataverse.xhtml
ICRAF - https://data.worldagroforestry.org/

**Comment by jggautier** [comment]
Closing in favor of https://github.com/IQSS/dataverse.harvard.edu/issues/62
