### ISSUE TITLE
Add links from Harvard Dataverse to Support site content 

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse.harvard.edu#64]
The plan for links between Harvard Dataverse and the Support site include links to some of the content on the support site being available from the navigation on Harvard Dataverse.

[Old mockup](https://docs.google.com/presentation/d/15sx4EzwmvTp8-JkPJsDL6wZjfuNfMJ-uYQOmwz8n2Vg/edit#slide=id.g4cefbf785a_0_109) shown below for context:
<img width="685" alt="Screen Shot 2020-02-24 at 10 12 01 AM" src="https://user-images.githubusercontent.com/15386424/75164015-24555a00-56ee-11ea-92c3-04eca92825fd.png">

New mockups (options 1 and 2 below) that address the issue. Both mockups move the link to contact support via the popup to the "Support" menu. Let me know if there are other options to consider. 

Option 1 – "About" as the label in the navigation, since people frequently look for an "About" link when they want to get basic, introductory info:
<img width="1114" alt="Harvard_Dataverse_home_nav_About" src="https://user-images.githubusercontent.com/15386424/75164198-6aaab900-56ee-11ea-90ce-66654b9e408f.png">

Option 2 – "Support" as the label in the navigation:
<img width="1114" alt="Harvard_Dataverser_home_nav_alt" src="https://user-images.githubusercontent.com/15386424/75164207-6e3e4000-56ee-11ea-999e-46beb03251aa.png">

**Comment by TaniaSchlatter** [comment]
Implications discussed:
- Change the existing "About" link config and adding additional config options to support the sub menu, or make all text links configurable 
- It would be easier to have a second fly-out menu for the items under "Support Home"
- Put "User Guide" in the new drop down?
- Languages would need to be considered/configured

**Comment by TaniaSchlatter** [comment]
[Document with a plan to move this forward](https://docs.google.com/document/d/1-_vUnxNSX3uaWKQoFaO91HtY3TZQDbsf-9vAzLXy-r0/edit)

Dwayne is working on mockups to add content about and links to support services.

**Comment by TaniaSchlatter** [comment]
Mockup with changes:

![Screen Shot 2020-09-15 at 11 08 37 AM](https://user-images.githubusercontent.com/15386424/93229149-4410a600-f744-11ea-94e9-b941d5f143d7.png)

**Comment by mheppler** [comment]
Revisions have been made to the `harvard-dataverse-homepage.html` file in the new `resourcesProd-2020-09-23.zip` resource file added to the Harvard Dataverse Customization folder in Google Drive.

<img width="1188" alt="Screen Shot 2020-09-23 at 11 31 28 AM" src="https://user-images.githubusercontent.com/687227/94034755-5c11a680-fd90-11ea-8497-2b30a018cc42.png">
