### ISSUE TITLE
Indexing: Failure to index one dataset, results in exception when clicked.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse.harvard.edu#69]
With v4.20, index all worked for all datasets but one. That one has an existing record but when you click on it, throws an exception.

Indexing directly throws an error.

Leonid reported seeing these errors in the log on page load:
```
[2020-04-13T14:54:04.331-0400] [glassfish 4.1] [WARNING] [] [javax.enterprise.resource.webcontainer.jsf.lifecycle] [tid: _ThreadID=105 _ThreadName=jk-connector(3)] [timeMillis: 1586804044331] [levelValue: 900] [[
  #{DatasetPage.init}: java.lang.NullPointerException
javax.faces.FacesException: #{DatasetPage.init}: java.lang.NullPointerException
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:118)
```
It looks like it's something with the author of the dataset: (L.A.)
```
Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.DatasetAuthor.isEmpty(DatasetAuthor.java:87)
	at edu.harvard.iq.dataverse.DataCitation.lambda$getAuthorsAndProducersFrom$1(DataCitation.java:738)
```

The dataset: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/2U2N87

**Comment by landreev** [comment]
So to me it looks like it may be more of a curation issue, rather than dev. - if it's just a matter of going into the db. and fixing whatever is wrong with the author for the dataset? 

But then it may also be something in our code, that allows a user to create a dataset with "bad" author field; or allows to edit it in a way that saves it, but then breaks the dataset...

The dataset passes our validation API btw - so it's not an outright constraint violation.

**Comment by landreev** [comment]
We have changed something about author affiliations in 4.20 - correct?
this is the line 87 of DatasetAuthor.java:
```
        return ( (affiliation==null || affiliation.getValue().trim().equals(""))
```
that throws a null pointer. so it looks like it is now possible to have an affiliation field that's no null; but has a null value. Hmm.
Also, there doesn't seem to be any other datasets in the db with this issue - at least this one is the only one that failed to reindex...

**Comment by jggautier** [comment]
> We have changed something about author affiliations in 4.20 - correct?

The PR at https://github.com/IQSS/dataverse/pull/6619 removes parenthesis from author affiliation values in the Search API results.

**Comment by djbrooke** [comment]
- Some investigation to see how this happened, and fix in prod
- Determine code fix and put up a PR

**Comment by sekmiller** [comment]
If we want to delete the offending record here is the diagnostic query(hat tip Leonid):

SELECT v.id, f.datasetfieldtype_id, t.name, fp.datasetversion_id
FROM datasetfieldvalue v, 
     datasetfield f, 
     datasetfield fp, 
     datasetfieldcompoundvalue fpv, 
     datasetfieldtype t 
WHERE v.datasetfield_id = f.id 
   AND f.datasetfieldtype_id = t.id 
   AND v.value IS null 
   AND t.id = 9 
   AND f.parentdatasetfieldcompoundvalue_id = fpv.id 
   AND fpv.parentdatasetfield_id = fp.id 
   AND fp.template_id IS null

The "v.id" in the result can be used in the delete query. 
   
   /4776468	- this is the id from the production clone that I had locally
   
   delete from datasetfieldvalue where id = xxxxxx;

**Comment by landreev** [comment]
Just to document it, this was fixed without running direct db queries; by creating a draft version (by edit -> save - no need to make any actual changes), then publishing, as a superuser, without incrementing the version. This updates the latest version, removing the empty/null values in the process. (and then deletes the draft)
