### ISSUE TITLE
Remove link to Harvard Dataverse Privacy Policy from Dataverse.org nav bar

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#7]
The Privacy Policy URL on the dataverse.harvard.edu points to:

http://best-practices.dataverse.org/harvard-policies/harvard-privacy-policy.html

and it should go to:

https://dataverse.org/best-practices/harvard-dataverse-privacy-policy

**Comment by pdurbin** [comment]
@djbrooke for now I re-enabled all of http://best-practices.dataverse.org but this content having to do with the privacy policy for Harvard Dataverse should go in the "About" website for Harvard Dataverse that's in the works.

**Comment by pdurbin** [comment]
Oh, for anyone who's curious, here's the Apache config file I re-enabled to get that best practices website working again: https://github.com/IQSS/dataverse.org/blob/master/deploy/files/etc/httpd/conf.d/1best-practices.dataverse.org.conf

We killed it during a meeting a few weeks ago. It's a a vhost on the server that also hosts http://guides.dataverse.org

**Comment by jggautier** [comment]
Now that the Harvard Dataverse Privacy Policy lives on https://support.dataverse.harvard.edu, the link on Dataverse.org should be removed. Updating the title on this issue.
