### ISSUE TITLE
Display and link to a new featured Covid-19 dataverse on the Harvard Dataverse home page

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse.harvard.edu#71]
Sonia and team are creating a curated Dataverse to contain data related to Covid-19. Mercè would like us to feature this dataverse and link to it from the Harvard Dataverse home page.

**Comment by TaniaSchlatter** [comment]
Static mock ups are done, digital mock ups are in progress.

**Comment by TaniaSchlatter** [comment]
Reviewed a version of the promo with Mercè. Feedback:

The position seems not quite right – competes with the search/find above. 
- try the promo above the rule (under the "Add" buttons)
- try the promo after the list of subjects, either above or below "All Data". May need to add some static dummy subjects to see how this looks. 

Add a few words (to come from Sonia) about the Dataverse.

**Comment by TaniaSchlatter** [comment]
Here is a shortened description to add this promo on the hope page:
"A curated collection of COVID-19 data deposited in the Harvard Dataverse repository"
![Screen Shot 2020-05-06 at 3 07 51 PM](https://user-images.githubusercontent.com/15386424/81217972-73035800-8fab-11ea-83a2-c38cf44be522.png)

**Comment by TaniaSchlatter** [comment]
We have approval. Moving ahead with this version:

<img width="1187" alt="Screen Shot 2020-05-07 at 11 51 17 AM" src="https://user-images.githubusercontent.com/15386424/81341572-c646da80-907f-11ea-990b-a81b10fd6218.png">

**Comment by mheppler** [comment]
@kcondon has moved the updated custom hmpg to production. Enjoy.

https://dataverse.harvard.edu/

<img width="1250" alt="Screen Shot 2020-05-08 at 4 53 36 PM" src="https://user-images.githubusercontent.com/687227/81448568-94e81080-914c-11ea-99fc-0c3248bfcc19.png">
