### ISSUE TITLE
Investigate production freezes

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse.harvard.edu#73]
Series of still unexplained production server freezes in the last few days. 
Since most of our stability issues in the past were load related I started looking for spikes and/or unusual use patterns. But it appears that neither memory nor threads were maxed out. Running with GC logging enabled showed available memory and no FGCs. 
Another symptom was that it was specifically the login page becoming unresponsive (timing out) while other pages appeared to be functioning. (LTS new service monitoring script was relying on loading the login page as a check - we probably suggested it to them at some point, under the assumption that it's a fast, lightweight page?) so that resulted in some restarts that were probably not immediately necessary. Users obviously can't do much when they can't log in. Still, some seemingly heavy pages - like large public datasets - appear to be loading just fine once this starts happening. I haven't yet confirmed what happens to existing login sessions. 
There is really not much inside the login page that it needs just to load. Only a few calls to the AuthenticationService. 
Do we have some bizarre condition where AuthenticationService becomes blocked, and other threads need to wait for something to finish before they can make their calls? @scolapasta and I were a little surprised ourselves that AuthenticationServiceBean is a singleton. Still, nothing immediately obvious there.

**Comment by landreev** [comment]
Oh crap. The fact that AuthenticationServiceBean is a @Singleton may indeed have something to do with this. It's a singleton, without any `@Lock` annotations... And, if I'm reading this right: https://docs.oracle.com/cd/E19798-01/821-1841/gipsz/index.html it then defaults to `@Lock(WRITE)` on all methods... Meaning, only one client may be calling any one method at the same time. So if the method AuthenticationServiceBean.getAuthenticationProvider() was for whatever reason hanging and locked by one client,  nobody else will be able to load the Login page - because it needs to call the method in its init(). 
(I appear to have easily confirmed the above experimentally)

**Comment by landreev** [comment]
Hmm, it's actually more than that - it's not just the individual methods, the entire AuthenticationServiceBean singleton class gets locked for **one client access at a time**. To any method. 
Again, this seems to be what the Oracle doc above says. 

Here's the experiment that confirms this: 
insert "sleep 60" into `AuthenticationServiceBean.getAuthenticationProviderIdsOfType()` (and an "I'm inside ... " log message of your liking...). 
Try to load loginpage.xhtml; it'll load with a 60 sec. delay. You're not going to be able to use any other AuthenticationServiceBean methods during this 60 sec. delay anywhere else in the application. (everybody is encouraged to verify this - to make sure I'm not seeing things). 

If this is what's been making the login page freeze in prod., why has it started biting us in the butt now? - that class has been a singleton throughout D4. What this must mean is that this does not cause problems, normally, because no methods inside AuthenticationServiceBean take long to execute, under normal circumstances.  But now something started happening, that ties one of the methods for an appreciable amount of time - and the login page (and all sorts of other functionality!) is now becoming unavailable during that window. 

(?? - emphasis on the "please verify" part above; I may be crazy too)

**Comment by landreev** [comment]
Looking at the history of it - @michbarsinai most likely meant this service bean to be responsible only for registering individual auth. service providers; and that's why it's a  @Singleton? - But then it was forgotten, and it got stuffed with methods that actually do work, on users and groups and their api tokens...

**Comment by scolapasta** [comment]
Hmm, that's a good point - that this was created for something that should be a Singleton and not be used often, but then we started using it for all Authentication related calls, include common, frequent ones.

It's still a little mystery of if anything changed with 4.20 that increased calls to a method in it?

@michbarsinai can you verify the intended design? Do we need to consider splitting this up into two (one Singleton, one not) EJBs?

**Comment by landreev** [comment]
Well, it says 
```
 * The AuthenticationManager is responsible for registering and listing
 * AuthenticationProviders. There's a single instance per application.
```
at the top. 
(alternatively, we could throw @Lock(Read) annotations on the methods that don't need to be locking...)

**Comment by landreev** [comment]
> ... if anything changed with 4.20 that increased calls to a method in it?

Well, there's a chance that nothing changed, on our end...  it may have been happening before at the same rate.  But then Tom wrote a script that would automatically restart the application as soon as the login page started timing out... 

But it's also possible that there's a user with so many "workflow comments" in the db - whatever they are - that the method getWorkflowCommentsByAuthenticatedUser() (also in there) legitimately takes 30 minutes. And they are just using Dataverse more often these days. (lol )

**Comment by michbarsinai** [comment]
@landreev - impressive bug research! I wasn't aware of the lock issues. 

@scolapasta The design intension was indeed prevent a case where we have have multiple factories and authentication providers hanging around in the application, and getting out of sync. There was no intension for it to deal with lengthy DB processes, so lock issue was not manifested.

It might be possible to just remove the `@Singleton` from the class definition, as long as the providers are not changed while the application is running... but maybe it's better to relocate long-running methods to other beans.

**Comment by landreev** [comment]
@michbarsinai Hi Michael! Hope things are good and you are well! - thanks for chiming in. 

At this point I'm just waiting for the login page to start timing out again; so I could make a core dump and then, presumably, figure out what's locking it. (but now that I'm watching it, of course it's not going to happen for a while).

**Comment by michbarsinai** [comment]
So I suggest fixing this by adding `boolean landreevWatching=true;` at the top of the method :-)

Keep well!

**Comment by landreev** [comment]
A status update: 

It seems clear that we'll want a PR in the main dataverse project removing any methods that we don't want to be locking from the current Singleton AuthenticationServiceBean. It should be straightforward. We can rename the Singleton service "AuthenticationProviderRegistrationService" and move the registration methods there. Leaving everything else in the current service, making it regular @Stateless. Or we can rename it too - "AuthenticatedUsersService"? - probably unnecessary. 

However, it still hasn't been confirmed, experimentally, what exactly was causing the login page freezes in production. It is extremely likely that it was related to the above - but we don't know what other part of the system was actually blocking access to the Auth. service, and/or what the long-running locking action was. Until last Tuesday, this was happening about once a weekday on one of the server nodes. I've been running scripts on both nodes since then waiting to take a full jstack snapshot and a heap dump of the app. as soon as the login page becomes unresponsive again. So we could find out for sure what's locking and blocking... Of course it hasn't happened again since then. 

(the reason I believe it was "extremely likely" to be "related to the above": the Login page is extremely lightweight; there's not much happening inside, except for a few calls to the AuthenticationService, mostly. Combined with what we discovered about the locking nature of access to that service; and the fact that other, more resource consuming pages kept working - it seems very likely to me that it had something to do with that)

**Comment by landreev** [comment]
(so, I'd like to wait a little more and try to find out for sure what causes the observed issue before we move to work on the service fix)

**Comment by landreev** [comment]
There's also a possibility that some crawler I blocked had been contributing to making that locking condition more likely to happen - who knows.

**Comment by landreev** [comment]
Happening now on app-2 - both jstack and jmap were able to produce output!

**Comment by landreev** [comment]
From a very brief look at the jstack trace, it is looking like it's hanging on an AuthenticationServiceBean call from FinalizeDatasetPublicationCommand.

**Comment by landreev** [comment]
I have resisted mentioning it, because it felt a little crazy - but I had a sense that this might be coinciding with users also experiencing delays publishing; which in turn may have been on account of some DataCite issues specifically.

**Comment by landreev** [comment]
There's also an "edit in progress" Dataverse-level lock... And that edit is clearly seen in jstack stuck waiting for access to AuthenticationServiceBean.

**Comment by landreev** [comment]
Anyway, I need to transfer the heap dumps to my local system and run Eclipse MAT on it.

**Comment by landreev** [comment]
If anyone wants to look at the thread stack trace: https://dvn-build.hmdc.harvard.edu/custom/jstack-long.txt

**Comment by landreev** [comment]
The weirdest thing is that it's looking like AuthenticationServiceBean is hanging on something really trivial - waiting for a response from the datbase looking up the authenticated user by id...

**Comment by michbarsinai** [comment]
Weird indeed. These lines, though:

```
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
	at com.sun.ejb.containers.CMCSingletonContainer._getContext(CMCSingletonContainer.java:141)
	at com.sun.ejb.containers.BaseContainer.getContext(BaseContainer.java:2579)
	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:1971)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:210)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy562.getAuthenticatedUser(Unknown Source)
```

Especially the CMCSingletonContainer obtaining a lock while calling the entity manager (the only thing happening in `getAuthenticatedUser`... can it be that the EM is locked because of the singleton lock?

I agree that starting with removing non-essential locks is a good strategy anyway. Event if it does not solve this issue, but will sure solve other issues down the road.

**Comment by landreev** [comment]
But is it really "obtaining a lock while calling the entity manager"? -  I was assuming it got the lock because it was inside getAuthenticatedUser; and the other threads were waiting for it to unlock before they could get use AuthenticationServiceBean themselves (and they would need to obtain a lock on the Singleton too before they can do that)... but then the first thread for some reason isn't able to finish what it's doing with the EM - so it keeps holding the method.
I.e., unless I'm missing something, I can't see how the EM itself is locked - ?

**Comment by michbarsinai** [comment]
Right. Looking at a CMCSingletonContainer code (I know that's not the right version though):

https://github.com/payara/Payara/blob/master/appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/CMCSingletonContainer.java#L84

There is some complex logic about which lock they are using. So the same lock might be re-used by two threads (there may be a clustered lookup for a distributed lock). Also, FindBugs is not happy with the method (per Javadoc comment). But again, not exact source code version, so might be a red herring.

**Comment by landreev** [comment]
It appears that this was happening with a dataset that actually was taking a long time to publish (possibly because Datacite was taking a while). Is it stuck simply because the AuthenticatedUser object has been modified by an external thread since the command started executing?? (and AuthenticatedUser does get modified a lot while the user is active; it has "lastlogintime" field, for ex.). 

But then the question again would be, why was it not happening all the time before.

**Comment by michbarsinai** [comment]
There seem to be 23 threads waiting on this lock.

![image](https://user-images.githubusercontent.com/1938468/82322667-8ec12200-99df-11ea-9d60-9e90eaee62a7.png)

**Comment by landreev** [comment]
Yeah, that's the whole point of these singleton locks - once something is using an AuthenticationServiceBean method, everybody else has to wait! And if something is hanging inside an AuthenticationServiceBean method, the system becomes paralyzed, because most things need to call it too. The stack trace just proves that this is what we've been seeing on our system. Some of these waiting threads are instances of the login page trying to execute its init() method - the login page timing out was the first and the most obvious manifestation of this starting to happen. But others are from all sorts of other things, users trying to save their edits, etc. Again, the system cannot function without things being able to call AuthenticaionServiceBean. 

I still can't offer a precise recipe for how to run into this condition on purpose - but I have a pretty good idea of how it got there. Note that there are 4 instances of `FinalizeDatasetPublicationCommand` command in that stack trace, running from 4 different threads. Looking at these threads in the heap dump in MAT, 3 of them are actually trying to publish the same dataset! That user reported having trouble publishing, specifically describing how the spinner would disappear and then "nothing happens" - no error messages, etc.  In other words - WE ARE ASKING FOR IT!! - when "nothing happens" in the UI, the user is all but encouraged to try clicking the publishing button again; not realizing it's still running. 

One disappointment is that I was kinda expecting to see one of these threads hanging on a long, timing out call to Datacite. But none of them are. One however is already past that point - calling the database inside `notifyUsersDatasetPublish(ctxt, theDataset);` (line 158). So, who knows, maybe Datacite was indeed the reason why the first attempt to publish took a while (or maybe it was something else); but now that they tried it the second and the third time, it's the database calls - since the commands are being executed in transactions, on the same objects - that are blocking each other (?) Normally, this would only result in these publishing attempts blocking each other - but with the evil Singleton in the mix, and the fact that one of the hanging database calls is inside a blocking method - it's blocking the entire system. 

After the server node above was killed, I tried to publish that dataset for the user again. The first time it took forever, and then it died with a deadlock exception from the database. I'm guessing since Glassfish had to be killed with -9, the database connections from the previous attempts were still alive, on the RDS side?? The second time around it took a while again - but then successfully completed. 
So we do know that the database was not happy about these competing publishing attempts.

**Comment by landreev** [comment]
(if anyone wants to kill some time looking at the heap dump - let me know... we really lucked out, in that this happened on app-2 with not much else going on, so the dump is manageable size-wise. but "manageable" is still 2.5GB of binary .hprof)
![Screen Shot 2020-05-19 at 10 06 35 AM](https://user-images.githubusercontent.com/737558/82337492-d5038a80-99b9-11ea-8ce7-1bbbbe36945d.png)

**Comment by landreev** [comment]
(I edited the long comment from earlier today, to correct some small things)

**Comment by michbarsinai** [comment]
I think at this point it's clear the refactor you've suggested will solve this, no?

**Comment by djbrooke** [comment]
@landreev is it OK if we close this one, between the patch and larger code change?

**Comment by landreev** [comment]
So yes, closing this issue; since we have an emergency patch in place in production (and have it ready to offer  to any other 4.20 installattion who starts experiencing this issue), and this hasn't happened since it was applied. We also have the still open #6918, for a  more thorough and clean refactoring that will go into v.5. 

Why this hasn't affected anyone else?  (assuming there are other prod.-size installations that have upgraded to v.4.20) - It really appears that what we were seeing in our production was really a perfect combination of 4 different conditions,  with all 4 required for the issue to become catastrophic. Of which one was introduced in v.4.20, and one appeared to be actually unique to our server... So, hopefully it's not going to happen to anyone else before v.5. But we'll see.
