### ISSUE TITLE
Add "Report Copyright Infringement" link in dataverse.harvard.edu footer

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#74]
We should add a link on the footer of dataverse.harvard.edu (both on the custom homepage and throughout the site) titled "Report Copyright Infringement" that links to https://www.harvard.edu/copyright-issue.

**Comment by mheppler** [comment]
Adding a new link to the footer similar to the Accessibility link that is already there.

<img width="1184" alt="Screen Shot 2020-07-28 at 11 03 57 AM" src="https://user-images.githubusercontent.com/687227/88683654-0ab3a680-d0c2-11ea-96d7-610738830a14.png">

Here is the revised code in the harvard-dataverse-footer.html, if anyone wants to do an official code review.

```
<script>
  //<![CDATA[
  $(document).ready(function () {
    $("#footer > div.container > div.row > div.col-sm-8.small > p").append("&#160;|&#160; <a href=\"https://www.harvard.edu/copyright-issue\" target=\"_blank\" rel=\"noopener\">Report Copyright Infringement</a> &#160;|&#160; <a href=\"https://accessibility.huit.harvard.edu/digital-accessibility-policy\" target=\"_blank\" rel=\"noopener\">Accessibility</a>");
  });
  //]]>
</script>
```

**Comment by pdurbin** [comment]
> harvard-dataverse-footer.html

Should this file go in this repo?

**Comment by kcondon** [comment]
@pdurbin Maybe slow this am but could you post a link? I prefer explicit info so there are no misunderstandings on my part 👍

**Comment by mheppler** [comment]
Resource ZIP `resourcesProd-2020-07-01.zip` containing updated `harvard-dataverse-footer.html` file can be found in Google Drive > Dataverse > Harvard Dataverse > Harvard Dataverse Customization.

`analytics-code.html` was also updated with changes related to 5.0 UI changes.

**Comment by kcondon** [comment]
@mheppler Thanks for the path, I think I can search on that but it implies I can navigate a hierarchy but I do not have those folders in my view.

**Comment by mheppler** [comment]
@kcondon it should work, but might as well hold off until 5.0 is deployed, unless you prefer to knock it off your deploy to-do list.

**Comment by kcondon** [comment]
@mheppler Thanks

**Comment by kcondon** [comment]
footer on both nodes, analytics code updated
