### ISSUE TITLE
Spike: finalize the plan for transition to Make Data Count, how to display the metrics, how to handle legacy counts

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse.harvard.edu#75]
Established Dataverse installations that have been operating for years might be reluctant to turn on Make Data Count (MDC) because the download counts will be reset to zero unless something is done to somehow copy the "classic" download counts into the new "datasetmetrics" database table that powers MDC download metrics. For example, Harvard Dataverse has over 10 million "classic" downloads:

![Screen Shot 2020-02-06 at 11 47 41 AM](https://user-images.githubusercontent.com/21006/73958876-8b91a280-48d6-11ea-865d-c0218a0979c8.png)

Many Dataverse installations probably don't have all the Apache (or Glassfish or whatever) access logs from years ago lying around but the database table `filedownload` could be used as a source for timestamps of downloads from the "classic" system. After standup on 2020-02-05 @djbrooke @kcondon talked about this and I made the following diagram (best to open it in a new window since the text is so small):

![make-data-count](https://user-images.githubusercontent.com/21006/73873945-9be74600-4820-11ea-800b-04ca1f45e90b.png)

source for the image above: [make-data-count.uml.txt](https://github.com/IQSS/dataverse/files/4166368/make-data-count.uml.txt)

This is what I added to the diagram, which is based on http://guides.dataverse.org/en/4.19/admin/make-data-count.html#architecture

```
== Historical Logging ==
sysadmin --> exportLogsApi : GET /api/admin/mdc/exportLogs
exportLogsApi --> log : all history from database
main.py --> log : read historical logs
main.py --> datasetMetrics : write metrics to datasetmetrics table (using SUSHI, as below)
main.py --> reports : send metrics to DataCite
```

This is a bit hand wavy because we'd still use SUSHI as indicated by the `Log Processing` part of the diagram.

Roughly, the idea is this:

- Create a new Dataverse API for sysadmins to use to export from Dataverse a series logs that are compatible with Counter Processor (one per month for 10 years, for example)
- Use Counter Processor to populate the new "datasetmetrics" table used by MDC by processing those logs that were exported.
- Use Counter Processor to send the historical data to DataCite.

See also pull request IQSS/dataverse#6543

- classic table: http://phoenix.dataverse.org/schemaspy/latest/tables/filedownload.html
- MDC table http://phoenix.dataverse.org/schemaspy/latest/tables/datasetmetrics.html

**Comment by jggautier** [comment]
Just an update based on recent discussion in the GREI "Use Metrics" committee: DataCite is working on a simpler method for sending metrics (requests and investigations).

During a recent GREI Open Metrics committee meeting, a DataCite representative recommended that those repositories that haven't been reporting these use metrics, such as Harvard's repository, wait until that simpler method is finished being tested and has been released for use.

This new method is being called a usage tracker and it involves adding a snippet of code on each dataset page. I don't know much else, including how it would be involved in converting a Dataverse repository's "classic" download counts to COUNTER compliant metrics.

@pdurbin do you know if the development of this usage tracker is described anywhere online yet?

**Comment by pdurbin** [comment]
@jggautier from the notes you may have noticed https://portal.productboard.com/71qotggkmbccdwzokuudjcsb/c/62-usage-stats-processing-as-a-service which I believe is the item on DataCite roadmap to watch for development of the usage tracker.

I believe the code is here: https://github.com/datacite/datacite-tracker

As you know, this issue is related, and (I think) more about setting up MDC for Harvard Dataverse (the old way at least, with log processing... maybe we need a fresh issue for the usage tracker):

- #3

(This issue #75 is a bit more of ensuring that the download counts aren't zero when we switch from the database counts to the MDC counts. This is something to get right for either solution, log processing or usage tracker. Another option is to show both counts, which is what https://github.com/IQSS/dataverse/issues/6542 is about.)

**Comment by mreekie** [comment]
Priority review with stefano:
- Added to the ordered backlog

**Comment by pdurbin** [comment]
Which MDC option do we plan to use for Harvard Dataverse? Backend log processing? Frontend/Javascript tracker?

**Comment by mreekie** [comment]
sizing:
 - this will involve a discussion with the right people to put a stake in the ground on which of the three options to take.
 - The right people include: Julian, Leonid, Phil.
 - Julian is aware of the right people to talk to and can bring them to the table.
   - Daniella from Dryad - they started using the new metrics.
- sized at a 10

See also: https://github.com/IQSS/dataverse/issues/6542

**Comment by landreev** [comment]
Linking the issue #IQSS/dataverse/issues/9025 in the main project - a lot of the more recent discussion concerning this issue was happening there. As we revisit it during this spike, let's make sure to take any potentially useful information there into consideration.

**Comment by pdurbin** [comment]
Discussed at standup. No objection to showing both counts.

The next step is probably to see if we can update and merge Jim's pull request:

- https://github.com/IQSS/dataverse/pull/6543

**Comment by pdurbin** [comment]
We gave the PR a 10

This one: https://github.com/IQSS/dataverse/pull/6543

**Comment by jggautier** [comment]
For the sake of posterity, I should say that although [I wrote](https://github.com/IQSS/dataverse.harvard.edu/issues/75#issuecomment-1452158055) that I'd to learn from admins of collections in Harvard Dataverse who generally rely on metrics, I wasn't able to talk with them about this. One of the things I wanted to learn was if it was necessary to show both counts.

Unfortunately @landreev let me know that my comment was taken to mean that these users would like both counts to show, which may or may not be true, and supported the idea of a solution where both counts are shown.
