### ISSUE TITLE
Change "Feedback" tab on the bottom of Harvard Dataverse

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse.harvard.edu#76]
Found during heuristic reviews April/May 2020 ([one example](https://docs.google.com/document/u/2/d/1tpc39Oo3QgfzfWm352istLteSHn06pM7jm1_Ku6yNAk/edit)): The term "Feedback" sets the expectation that clicking the tab will open up a form to provide feedback on the Harvard Dataverse application:

"It looks and sounds like a chat function where you can talk to a specialist found on other websites. Repurposing that bottom corner to allow for more help options can be useful and can leave less room for error. "

We had an increase in responses using the form in June and July 2020, some with people who seem qualified and want to participate in testing, and some who want to provide feedback.

I edited the form to accept general feedback. 

We should edit the text of the popup, so that people know they can add feedback and submit their name to participate in usability testing. 

![Screen Shot 2020-07-24 at 3 54 17 PM](https://user-images.githubusercontent.com/15386424/88430424-6f22ed00-cdc6-11ea-8b02-1bea27402f25.png)

**Comment by TaniaSchlatter** [comment]
Danny and Mercè also agree to remove it.

**Comment by TaniaSchlatter** [comment]
I edited the initial comment to support keeping the form, after finding it is being used.

**Comment by TaniaSchlatter** [comment]
Given the number of responses we are having to the form this month, I think we should keep it a little longer now that it has been edited and has a text area for feedback. 

Can we make the tab itself launch the form directly?

**Comment by mheppler** [comment]
Removed the panel slide up functionality, and added a tooltip to the Feedback btn, in order to simplify the component as well as remove the need to revise the Learn More link text. The improved button functionality now proves the use a single click path to the newly revised feedback form.

<img width="247" alt="Screen Shot 2020-07-28 at 10 56 11 AM" src="https://user-images.githubusercontent.com/687227/88682870-2cf8f480-d0c1-11ea-8195-cda43f8460a2.png">

Will provide a ZIP of all the resource files in the Google Drive directory for Harvard Dataverse customization. Here is the revised code if anyone wants to do an official code review.

```
<style>
#feedbackTab {position:fixed; bottom:0; right:50px;}
#feedbackTab a.btn-feedback {border-bottom-right-radius:0; border-bottom-left-radius:0;}
.btn-feedback {background-color:#C55B28; border-color:#C55B28; color:#fff;}
.btn-feedback:hover, .btn-feedback:focus,
.btn-feedback:active, .btn-feedback.active {background-color:#b05124; border-color: #9b471f; color:#fff;}
</style>

<div id="feedbackTab">
    <a class="btn btn-feedback bootstrap-button-tooltip" href="https://goo.gl/forms/p7uu3GfiWYSlJrsi1" role="button" target="_blank" rel="noopener"  aria-label="Help improve Dataverse!" data-original-title="Help improve Dataverse!">
        Feedback
    </a>
</div>
```

**Comment by mheppler** [comment]
Resource ZIP `resourcesProd-2020-07-01.zip` containing updated `harvard-dataverse-footer.html` file can be found in Google Drive > Dataverse > Harvard Dataverse > Harvard Dataverse Customization.

**Comment by kcondon** [comment]
new footer has been moved to both web servers.
