### ISSUE TITLE
Ingest ~30 Files on dataverse.harvard.edu that are over the ingest limit

### ISSUE THREAD

**Issue by bleonard33** [IQSS/dataverse.harvard.edu#77]
I have two data sets with 55 and 63 files for which I am trying to effectively replace with updated versions, but am running into issues where many of the files are failing to convert to the tab-delimited archival format. For the smaller set, almost all of the files are failing and the larger set, about half. I am uploading the files in Stata .dta format to the Harvard Dataverse (v4.20). 

Upon initial uploading, the sets will lock for ingestion, but then seem to complete and return successful email messages regarding completed ingestion for only a subset of the files. Previously, it seemed as though Dataverse would flag failed ingestions with the red triangle symbol, but now these seem to be failing silently in the console by only allowing direct downloads without the option to Explore the files like the successfully ingested ones. Deleting and re-uploading the batch of failed files leads to varying success, but generally seems to only add a small number of files to the successful batch, if any at all.

**Comment by djbrooke** [comment]
(also transferring to https://github.com/IQSS/dataverse.harvard.edu for better tracking)

**Comment by bleonard33** [comment]
Hey @djbrooke, thanks for helping out with this. I spoke with my manager and we'd love to coordinate getting these ingested if you're able to and we're fine waiting a few weeks to do so. We went ahead and released the version of the files as just Stata in the meantime, so no big rush on our end. Thanks!

**Comment by landreev** [comment]
Hello, 
This task somehow ended  up on the back burner for a while. But all the large Stata files in the 2 datasets above have now been ingested as tabular data. 
Please note that we ingested them without creating new Draft versions. I.e. the latest published versions of the 2 datasets are now showing these files as tabular data. 
Best, 
-Leonid

**Comment by djbrooke** [comment]
Hi @bleonard33 - see the note from Leonid above. Sorry for the delay on this. I'll close this issue but feel free to comment if you have any questions!

Thanks @landreev !
