### ISSUE TITLE
Point to GDCC Previewers instead of QDR

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#78]
We should use the GDCC previewers in their new location of https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers instead of from QDR, as we're currently missing out on updates and are starting to take on QDR branding.

**Comment by qqmyers** [comment]
And I'm contemplating limiting the CORS AllowedOrigins as discussed in https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers/wiki/Using-Previewers-with-download-redirects-from-S3 which would be a breaking change from the QDR repo...

**Comment by kcondon** [comment]
Done except did not add hypothesis previewer at Jim's suggestion
