### ISSUE TITLE
Add "generic" large stores

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#89]
In #87 we added some organization-specific stores for two groups. Following a discussion in dv-tech I'd like to expand this add a few more stores that we can apply generically across the app. The advantage of this generic approach is that we don't need to specify stores for specific organizations and restart the app, the disadvantage is that we may not be able to do chargebacks or other store-specific monitoring. We can always change the stores later if needed. I'd like to suggest adding the following generic stores:

- 5 GB
- 10 GB
- 25 GB
- 50 GB

Thoughts/discussion welcome about anything I'm missing here or anything that could be improved.

**Comment by landreev** [comment]
We now have 4 extra stores: 
```
S3 Medium
S3 Large
S3 Extra Large
S3 XXL
```
(these are the labels that are showing in the pulldown menus; the store ids are `s3m, s3l, s3xl` and `s3xxl` respectively)

The limits are 5, 10, 25 and 50GB respectively, as specified above. 
These labels, ids and limits can be easily changed later if needed.

**Comment by djbrooke** [comment]
Thanks @landreev for implementing these! This is a big step for larger data support in Harvard Dataverse. I'm going to close this out.
