### ISSUE TITLE
Update Privacy Policy link on dataverse.harvard.edu

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#90]
The Privacy Policy at the bottom of dataverse.harvard.edu goes to 

http://best-practices.dataverse.org/harvard-policies/harvard-privacy-policy.html

It should point to 

https://support.dataverse.harvard.edu/harvard-dataverse-privacy-policy

**Comment by kcondon** [comment]
Done

**Comment by djbrooke** [comment]
Perfect, thanks!
