### ISSUE TITLE
Homepage Data Viz Instance

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse.harvard.edu#93]
We recently added some scripts (https://github.com/IQSS/dataverse-homepage-viz/pull/8) to populate data that the visualization can use. I'd like to:

- Set up this script to run against production and put the data somewhere
- Have the visualization use this data 

My goal is to see how the visualization looks looks against production data and determine if we want to tweak anything, or if it's good to go and we can move forward on our plans to embed it somewhere on the home page.

**Comment by TaniaSchlatter** [comment]
Eli Munn is working with the data. He is refining an option that shows 3 levels of hierarchy as subject categories. To dos:

- define categories for subjects, so there are 5-7
- assign colorblind safe colors (sent via email)
- add icons to help demonstrate different subject categories (in addition to color, to help with accessibility)
- enable click to hold, and ability for names of dataverses to function as links 
- complete the display of "ancestor" dataverses
- show the number of datasets
- work to have the visualization shift to fit a scalable aspect ratio. Possibly disable click on the visualization, and click on subject category name instead. 
- we do not need to show the word "Dataverse" in the titles of the dataverses. We will add a title for the visualization that includes "Dataverse"
- truncate dataverse names that are too long
- limit dataverses shown to maximum 1,000 datasets, and possibly some minimum number of datasets. Plan to include this "about" information on the web page along with credits.

**Comment by TaniaSchlatter** [comment]
Eli has posted the code: https://github.com/e-munn/dataverse-homepage-tree
I am working with Dwayne on incorporating the visualization on the home page.

**Comment by TaniaSchlatter** [comment]
it is unlikely we will go forward with the visualization.
