### ISSUE TITLE
Google Search Results Display Numerous Bad (Spam) links to Harvard Dataverse

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse.harvard.edu#98]
This was found by Gary: https://www.google.com/search?q=microsoft+site%3Adataverse.harvard.edu&rlz=1C5CHFA_enUS880US881&oq=microsoft+site%3Adataverse.harvard.edu&aqs=chrome..69i57.8818j1j7&sourceid=chrome&ie=UTF-8

By nature of the names it appears to be promotional spam which likely was deleted by curation team. If it had been crawled by Google before it was deleted, would they live on for a time before being dropped? I think I'd seen a way to inform Google of dead links so that might be something to investigate, assuming this is a result of spam or even regardless of the cause.

**Comment by jggautier** [comment]
I agree, those are the spam dataverses and datasets the curation team deleted or that the SpamAssassin deleted. There are still some results from the "casino" related spam in the search results, too. They should all be dropped from Google's search results eventually.

If we didn't want to wait, I think https://support.google.com/webmasters/answer/9689846?hl=en is a good place to start for options for removing pages from Google's search results. We were considering these when we were moving the Harvard Dataverse policy documents around on the support site, but we decided to wait until Google re-crawled the site and dropped the pages that didn't exist anymore.

There's an option in the Search Console to submit URLs for deletion but Google suggests resubmitting a sitemap if there are a lot of pages. Would it be possible to resubmit a sitemap that includes all of the URLs we don't want in Google's search results? Then we'd have to get those URLs. Maybe we could we use the URLs of pages that the SpamAssassin's deleted and that are in the actionlogrecord table (that curation staff have deleted).

**Comment by jggautier** [comment]
Whoops, didn't notice that @djbrooke replied in an internal Slack thread that a sitemap was resubmitted to Google which hopefully will speed up their re-crawl process.

@djbrooke, should this GitHub issue stay open until we see that https://www.google.com/search?q=microsoft+site%3Adataverse.harvard.edu&rlz=1C5CHFA_enUS880US881&oq=microsoft+site%3Adataverse.harvard.edu doesn't return the old spam?

**Comment by jggautier** [comment]
Search results look like they're in much better shape. No spam when I checked that Google search link in [the original post](https://github.com/IQSS/dataverse.harvard.edu/issues/98#issue-792346528). Top results was one dataset with only an article. Just deaccessioned that dataset. Going to close this issue. Volume of spam has gone way down I think since spam assassin was turned on.
